package protobuf

import (
	"context"
	"fmt"
	"log"
	"strings"
	"time"

	"e2e/helpers"
	"github.com/google/go-github/v62/github"
)

const providerRepoName = "substrate-test-provider"
const consumerRepoName = "substrate-test-consumer"

func RunAll(ctx context.Context, client *github.Client, owner string) {
	log.Println("Starting Protobuf Automated Test Suite...")
	RunBreaking(ctx, client, owner)
	RunSafe(ctx, client, owner)
	RunOverride(ctx, client, owner)
	RunWarning(ctx, client, owner)
}

func RunSafe(ctx context.Context, client *github.Client, owner string) {
	executeScenario(ctx, client, owner, "Protobuf Safe Extension",
		defaultSubstrateYaml(), defaultProto(),
		defaultSubstrateYaml(), addedFieldProto(),
		"All Clear", "")
}

func RunBreaking(ctx context.Context, client *github.Client, owner string) {
	executeScenario(ctx, client, owner, "Protobuf Breaking Change",
		defaultSubstrateYaml(), defaultProto(),
		defaultSubstrateYaml(), changedFieldTypeProto(),
		"BREAKING", "PROTO_FIELD_TYPE_CHANGED")
}

func RunWarning(ctx context.Context, client *github.Client, owner string) {
	executeScenario(ctx, client, owner, "Protobuf Warnings Only",
		defaultSubstrateYaml(), defaultProto(),
		defaultSubstrateYaml(), changedPackageProto(),
		"Warnings Only", "PROTO_PACKAGE_CHANGED")
}

func RunOverride(ctx context.Context, client *github.Client, owner string) {
	executeScenario(ctx, client, owner, "Protobuf Config Override",
		defaultSubstrateYaml(), defaultProto(),
		overrideSubstrateYaml(), changedFieldTypeProto(),
		"All Clear", "")
}

func executeScenario(ctx context.Context, client *github.Client, owner, scenarioName, baseConfig, baseSchema, prConfig, prSchema, expectedStatus, expectedRule string) {
	log.Printf("=== Running Scenario: %s ===", scenarioName)

	log.Println("Seeding the main branch with baseline files...")
	helpers.SeedFile(ctx, client, owner, providerRepoName, "substrate.yaml", "main", baseConfig)
	helpers.SeedFile(ctx, client, owner, providerRepoName, "user.proto", "main", baseSchema)

	// Seed the consumer!
	consumerConfig := fmt.Sprintf(`service: test-consumer
consumers:
  - name: "test-provider"
    type: protobuf
    source: "github.com/%s/%s"
    path: "user.proto"
    branch: "main"`, owner, providerRepoName)

	helpers.SeedFile(ctx, client, owner, consumerRepoName, "substrate.yaml", "main", consumerConfig)
	helpers.SeedFile(ctx, client, owner, consumerRepoName, "user.proto", "main", baseSchema)

	log.Println("Waiting 15s for the Registry API to sync baselines...")
	time.Sleep(15 * time.Second)

	prBranch := fmt.Sprintf("e2e-proto-%d", time.Now().Unix())
	log.Printf("Creating branch %s...", prBranch)
	ref, _, err := client.Git.GetRef(ctx, owner, providerRepoName, "refs/heads/main")
	if err != nil { log.Fatalf("Failed to get main ref: %v", err) }

	_, _, err = client.Git.CreateRef(ctx, owner, providerRepoName, &github.Reference{
		Ref: github.String("refs/heads/" + prBranch),
		Object: &github.GitObject{ SHA: ref.Object.SHA },
	})
	if err != nil { log.Fatalf("Failed to create branch: %v", err) }

	log.Println("Pushing PR changes...")
	helpers.SeedFile(ctx, client, owner, providerRepoName, "substrate.yaml", prBranch, prConfig)
	helpers.SeedFile(ctx, client, owner, providerRepoName, "user.proto", prBranch, prSchema)

	log.Println("Opening Pull Request...")
	pr, _, err := client.PullRequests.Create(ctx, owner, providerRepoName, &github.NewPullRequest{
		Title: github.String(fmt.Sprintf("Automated E2E: %s", scenarioName)),
		Head:  github.String(prBranch),
		Base:  github.String("main"),
		Body:  github.String("Automated test generated by Substrate E2E suite."),
	})
	if err != nil { log.Fatalf("Failed to create PR: %v", err) }
	log.Printf("Created PR: %s", pr.GetHTMLURL())

	log.Println("Polling for Substrate PR comment (waiting up to 60s)...")
	var foundComment *github.IssueComment
	for i := 0; i < 20; i++ {
		time.Sleep(3 * time.Second)
		comments, _, err := client.Issues.ListComments(ctx, owner, providerRepoName, pr.GetNumber(), nil)
		if err != nil {
			log.Fatalf("❌ FAILED: Could not list PR comments: %v", err)
		}

		for _, comment := range comments {
			if strings.Contains(comment.GetBody(), "Substrate") {
				if strings.Contains(comment.GetBody(), expectedStatus) {
					if expectedRule == "" || strings.Contains(comment.GetBody(), expectedRule) {
						foundComment = comment
						break
					}
				}
			}
		}
		if foundComment != nil {
			break
		}
	}

	if foundComment == nil {
		if expectedRule != "" {
			log.Fatalf("❌ FAILED: Substrate bot did not post '%s' comment with rule '%s' within 60 seconds.", expectedStatus, expectedRule)
		} else {
			log.Fatalf("❌ FAILED: Substrate bot did not post '%s' comment within 60 seconds.", expectedStatus)
		}
	} else {
		if expectedRule != "" {
			log.Printf("✅ SUCCESS: Found expected status '%s' and asserted rule '%s'!", expectedStatus, expectedRule)
		} else {
			log.Printf("✅ SUCCESS: Found expected status '%s'!", expectedStatus)
		}
	}

	log.Println("Cleaning up PR and branch...")
	_, _, _ = client.PullRequests.Edit(ctx, owner, providerRepoName, pr.GetNumber(), &github.PullRequest{State: github.String("closed")})
	_, _ = client.Git.DeleteRef(ctx, owner, providerRepoName, "refs/heads/"+prBranch)
}

func defaultSubstrateYaml() string {
	return `service: test-provider-proto
schema_type: protobuf
spec_path: user.proto
`
}

func overrideSubstrateYaml() string {
	return `service: test-provider-proto
schema_type: protobuf
spec_path: user.proto

overrides:
  - rule_id: PROTO_FIELD_TYPE_CHANGED
    path: schema.proto:6
    reason: "E2E testing Protobuf override functionality"
    approved_by: "e2e-bot@example.com"
    expires: "2099-12-31"
`
}

func defaultProto() string {
	return `syntax = "proto3";

package myorg.v1;

message User {
  int32 id = 1;
  string name = 2;
}
`
}

func addedFieldProto() string {
	return `syntax = "proto3";

package myorg.v1;

message User {
  int32 id = 1;
  string name = 2;
  string email = 3;
}
`
}

func changedFieldTypeProto() string {
	return `syntax = "proto3";

package myorg.v1;

message User {
  string id = 1; // Changed from int32 to string
  string name = 2;
}
`
}

func changedPackageProto() string {
	return `syntax = "proto3";

package myorg.v2; // Changed package name

message User {
  int32 id = 1;
  string name = 2;
}
`
}
