image:
  repository: substrate/ebpf-probe
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  privileged: true

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
