package avro

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"strings"
	"time"

	"e2e/helpers"
	"github.com/google/go-github/v62/github"
)

const providerRepoName = "substrate-test-provider"
const consumerRepoName = "substrate-test-consumer"

func startMockRegistry() *http.Server {
	mux := http.NewServeMux()
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		// Just simulate compat check
		// For E2E we know "safeSchema" is compatible, "breakingSchema" is incompatible
		if r.Method == "POST" && strings.Contains(r.URL.Path, "compatibility/subjects") {
			w.Header().Set("Content-Type", "application/vnd.schemaregistry.v1+json")
			w.WriteHeader(200)

			// We can figure out if it's breaking or safe based on a header or something, but actually
			// just the URL or body. If it contains "new_field", we say it's compatible.
			// Actually let's just make it a dumb mock:
			if strings.Contains(r.URL.Path, "test-subject-incompatible") {
				w.Write([]byte(`{"is_compatible":false, "messages":["Field removed"]}`))
			} else {
				w.Write([]byte(`{"is_compatible":true}`))
			}
			return
		}
		w.WriteHeader(404)
	})

	server := &http.Server{Addr: ":8081", Handler: mux}
	go func() {
		if err := server.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.Fatalf("Failed to start mock registry: %v", err)
		}
	}()
	time.Sleep(1 * time.Second) // Wait for server to start
	return server
}

func RunAll(ctx context.Context, client *github.Client, owner string) {
	log.Println("Starting Avro Automated Test Suite...")
	server := startMockRegistry()
	defer server.Close()

	RunBreaking(ctx, client, owner)
	RunSafe(ctx, client, owner)
	RunOverride(ctx, client, owner)
}

func RunSafe(ctx context.Context, client *github.Client, owner string) {
	executeScenario(ctx, client, owner, "Avro Safe Extension",
		defaultSubstrateYaml("test-subject"), defaultSchema(),
		defaultSubstrateYaml("test-subject"), safeSchema(),
		"All Clear", "")
}

func RunBreaking(ctx context.Context, client *github.Client, owner string) {
	executeScenario(ctx, client, owner, "Avro Breaking Change",
		defaultSubstrateYaml("test-subject"), defaultSchema(),
		defaultSubstrateYaml("test-subject-incompatible"), breakingSchema(),
		"BREAKING", "AVRO_INCOMPATIBLE")
}

func RunOverride(ctx context.Context, client *github.Client, owner string) {
	executeScenario(ctx, client, owner, "Avro Config Override",
		defaultSubstrateYaml("test-subject"), defaultSchema(),
		overrideSubstrateYaml("test-subject-incompatible"), breakingSchema(),
		"All Clear", "")
}

func executeScenario(ctx context.Context, client *github.Client, owner, scenarioName, baseConfig, baseSchema, prConfig, prSchema, expectedStatus, expectedRule string) {
	log.Printf("=== Running Scenario: %s ===", scenarioName)

	log.Println("Seeding the main branch with baseline files...")
	helpers.SeedFile(ctx, client, owner, providerRepoName, "substrate.yaml", "main", baseConfig)
	helpers.SeedFile(ctx, client, owner, providerRepoName, "user.avsc", "main", baseSchema)

	// Seed the consumer
	consumerConfig := fmt.Sprintf(`service: test-consumer
consumers:
  - name: "test-provider"
    type: avro
    source: "github.com/%s/%s"
    path: "user.avsc"
    branch: "main"`, owner, providerRepoName)

	helpers.SeedFile(ctx, client, owner, consumerRepoName, "substrate.yaml", "main", consumerConfig)
	helpers.SeedFile(ctx, client, owner, consumerRepoName, "user.avsc", "main", baseSchema)

	log.Println("Waiting 15s for the Registry API to sync baselines...")
	time.Sleep(15 * time.Second)

	prBranch := fmt.Sprintf("e2e-avro-%d", time.Now().Unix())
	log.Printf("Creating branch %s...", prBranch)
	ref, _, err := client.Git.GetRef(ctx, owner, providerRepoName, "refs/heads/main")
	if err != nil {
		log.Fatalf("Failed to get main ref: %v", err)
	}

	_, _, err = client.Git.CreateRef(ctx, owner, providerRepoName, &github.Reference{
		Ref:    github.String("refs/heads/" + prBranch),
		Object: &github.GitObject{SHA: ref.Object.SHA},
	})
	if err != nil {
		log.Fatalf("Failed to create branch: %v", err)
	}

	log.Println("Pushing PR changes...")
	helpers.SeedFile(ctx, client, owner, providerRepoName, "substrate.yaml", prBranch, prConfig)
	helpers.SeedFile(ctx, client, owner, providerRepoName, "user.avsc", prBranch, prSchema)

	log.Println("Opening Pull Request...")
	pr, _, err := client.PullRequests.Create(ctx, owner, providerRepoName, &github.NewPullRequest{
		Title: github.String(fmt.Sprintf("Automated E2E: %s", scenarioName)),
		Head:  github.String(prBranch),
		Base:  github.String("main"),
		Body:  github.String("Automated test generated by Substrate E2E suite."),
	})
	if err != nil {
		log.Fatalf("Failed to create PR: %v", err)
	}
	log.Printf("Created PR: %s", pr.GetHTMLURL())

	log.Println("Polling for Substrate PR comment (waiting up to 60s)...")
	var foundComment *github.IssueComment
	for i := 0; i < 20; i++ {
		time.Sleep(3 * time.Second)
		comments, _, err := client.Issues.ListComments(ctx, owner, providerRepoName, pr.GetNumber(), nil)
		if err != nil {
			log.Fatalf("❌ FAILED: Could not list PR comments: %v", err)
		}

		for _, comment := range comments {
			if strings.Contains(comment.GetBody(), "Substrate") {
				if strings.Contains(comment.GetBody(), expectedStatus) {
					if expectedRule == "" || strings.Contains(comment.GetBody(), expectedRule) {
						foundComment = comment
						break
					}
				}
			}
		}
		if foundComment != nil {
			break
		}
	}

	if foundComment == nil {
		if expectedRule != "" {
			log.Fatalf("❌ FAILED: Substrate bot did not post '%s' comment with rule '%s' within 60 seconds.", expectedStatus, expectedRule)
		} else {
			log.Fatalf("❌ FAILED: Substrate bot did not post '%s' comment within 60 seconds.", expectedStatus)
		}
	} else {
		if expectedRule != "" {
			log.Printf("✅ SUCCESS: Found expected status '%s' and asserted rule '%s'!", expectedStatus, expectedRule)
		} else {
			log.Printf("✅ SUCCESS: Found expected status '%s'!", expectedStatus)
		}
	}

	log.Println("Cleaning up PR and branch...")
	_, _, _ = client.PullRequests.Edit(ctx, owner, providerRepoName, pr.GetNumber(), &github.PullRequest{State: github.String("closed")})
	_, _ = client.Git.DeleteRef(ctx, owner, providerRepoName, "refs/heads/"+prBranch)
}

func defaultSubstrateYaml(subject string) string {
	return fmt.Sprintf(`service: test-provider-avro
schema_type: avro
spec_path: user.avsc
avro:
  schema_registry_url: http://localhost:8081
  subject: %s
`, subject)
}

func overrideSubstrateYaml(subject string) string {
	return fmt.Sprintf(`service: test-provider-avro
schema_type: avro
spec_path: user.avsc
avro:
  schema_registry_url: http://localhost:8081
  subject: %s

overrides:
  - rule_id: AVRO_INCOMPATIBLE
    path: %s
    reason: "E2E testing Avro override functionality"
    approved_by: "e2e-bot@example.com"
    expires: "2099-12-31"
`, subject, subject)
}

func defaultSchema() string {
	return `{
  "type": "record",
  "name": "User",
  "fields": [
    {"name": "id", "type": "int"},
    {"name": "name", "type": "string"}
  ]
}`
}

func safeSchema() string {
	return `{
  "type": "record",
  "name": "User",
  "fields": [
    {"name": "id", "type": "int"},
    {"name": "name", "type": "string"},
    {"name": "email", "type": "string", "default": ""}
  ]
}`
}

func breakingSchema() string {
	return `{
  "type": "record",
  "name": "User",
  "fields": [
    {"name": "id", "type": "int"}
  ]
}`
}
