apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "substrate-ebpf.fullname" . }}
  labels:
    {{- include "substrate-ebpf.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "substrate-ebpf.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "substrate-ebpf.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: true
      hostPID: true
      serviceAccountName: {{ include "substrate-ebpf.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: sys-kernel-debug
              mountPath: /sys/kernel/debug
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: sys-kernel-debug
          hostPath:
            path: /sys/kernel/debug
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
