CREATE TABLE IF NOT EXISTS org_webhooks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org VARCHAR(255) NOT NULL,
    url TEXT NOT NULL,
    secret VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
