package openapi

import (
	"context"
	"fmt"
	"log"
	"strings"
	"time"

	"e2e/helpers"

	"github.com/google/go-github/v62/github"
)

const (
	providerRepoName = "substrate-test-provider"
	consumerRepoName = "substrate-test-consumer" // Will be seeded later when implementing cross-repo
)

func Run(ctx context.Context, client *github.Client, owner string) {
	log.Println("Starting OpenAPI Automated Test...")

	// Step 0: Seed the Main Branch
	log.Println("Seeding the main branch with baseline files...")
	helpers.SeedFile(ctx, client, owner, providerRepoName, "substrate.yaml", "main", `service: test-provider-api
schema_type: openapi
spec_path: openapi.yaml
`)
	helpers.SeedFile(ctx, client, owner, providerRepoName, "openapi.yaml", "main", `openapi: "3.0.0"
info:
  title: Provider API
  version: "1.0.0"
paths:
  /users:
    get:
      summary: List users
      responses:
        "200":
          description: OK
  /users/{id}:
    get:
      summary: Get user by ID
      responses:
        "200":
          description: OK
`)
	
	// Wait a moment for webhooks to sync the registry
	log.Println("Waiting 5s for the Registry API to sync baselines...")
	time.Sleep(5 * time.Second)

	branchName := fmt.Sprintf("e2e-openapi-%d", time.Now().Unix())

	// Step 1: Branch Creation
	log.Printf("Creating branch %s on %s...", branchName, providerRepoName)
	ref, _, err := client.Git.GetRef(ctx, owner, providerRepoName, "refs/heads/main")
	if err != nil {
		log.Fatalf("Failed to get main ref: %v", err)
	}

	newRef := &github.Reference{
		Ref: github.String("refs/heads/" + branchName),
		Object: &github.GitObject{
			SHA: ref.Object.SHA,
		},
	}
	
	_, _, err = client.Git.CreateRef(ctx, owner, providerRepoName, newRef)
	if err != nil {
		log.Fatalf("Failed to create branch: %v", err)
	}

	// Step 2: Push breaking change
	log.Println("Pushing breaking change to openapi.yaml...")
	breakingSchema := `openapi: "3.0.0"
info:
  title: Provider API
  version: "1.0.0"
paths:
  /users:
    get:
      summary: List users
      responses:
        "200":
          description: OK
` // We removed /users/{id}

	fileContent, _, _, err := client.Repositories.GetContents(ctx, owner, providerRepoName, "openapi.yaml", &github.RepositoryContentGetOptions{Ref: branchName})
	if err != nil {
		log.Fatalf("Failed to get file contents: %v", err)
	}

	opts := &github.RepositoryContentFileOptions{
		Message: github.String("test: automated breaking change"),
		Content: []byte(breakingSchema),
		SHA:     fileContent.SHA,
		Branch:  github.String(branchName),
	}
	_, _, err = client.Repositories.UpdateFile(ctx, owner, providerRepoName, "openapi.yaml", opts)
	if err != nil {
		log.Fatalf("Failed to update file: %v", err)
	}

	// Step 3: Open PR
	log.Println("Opening Pull Request...")
	pr, _, err := client.PullRequests.Create(ctx, owner, providerRepoName, &github.NewPullRequest{
		Title:               github.String("Automated E2E Test: OpenAPI Breaking Change"),
		Head:                github.String(branchName),
		Base:                github.String("main"),
		Body:                github.String("Automated test PR generated by Substrate E2E suite."),
		MaintainerCanModify: github.Bool(true),
	})
	if err != nil {
		log.Fatalf("Failed to create PR: %v", err)
	}
	log.Printf("Created PR: %s", pr.GetHTMLURL())

	// Step 4: Poll for Substrate Comment
	log.Println("Polling for Substrate PR comment (waiting up to 60s)...")
	var foundComment *github.IssueComment
	for i := 0; i < 20; i++ {
		time.Sleep(3 * time.Second)
		comments, _, err := client.Issues.ListComments(ctx, owner, providerRepoName, pr.GetNumber(), nil)
		if err != nil {
			log.Printf("Error fetching comments: %v", err)
			continue
		}
		for _, comment := range comments {
			if strings.Contains(comment.GetBody(), "BREAKING") && strings.Contains(comment.GetBody(), "Substrate") {
				foundComment = comment
				break
			}
		}
		if foundComment != nil {
			break
		}
	}

	if foundComment == nil {
		log.Fatalf("❌ FAILED: Substrate bot did not post a breaking change comment within 60 seconds.")
	} else {
		log.Println("✅ SUCCESS: Substrate bot posted the breaking change comment!")
	}

	// Step 5: Cleanup
	log.Println("Cleaning up PR and branch...")
	_, _, err = client.PullRequests.Edit(ctx, owner, providerRepoName, pr.GetNumber(), &github.PullRequest{
		State: github.String("closed"),
	})
	if err != nil {
		log.Printf("Failed to close PR: %v", err)
	}
	
	_, err = client.Git.DeleteRef(ctx, owner, providerRepoName, "refs/heads/"+branchName)
	if err != nil {
		log.Printf("Failed to delete branch: %v", err)
	}
	
	log.Println("🎉 OpenAPI Test Completed Successfully!")
}
