package openapi

import (
	"context"
	"fmt"
	"log"
	"strings"
	"time"

	"e2e/helpers"

	"github.com/google/go-github/v62/github"
)

const providerRepoName = "substrate-test-provider"

func RunAll(ctx context.Context, client *github.Client, owner string) {
	log.Println("Starting OpenAPI Automated Test Suite...")
	RunBreaking(ctx, client, owner)
	RunSafe(ctx, client, owner)
	RunOverride(ctx, client, owner)
	RunWarning(ctx, client, owner)
	log.Println("🎉 All OpenAPI Scenarios Completed Successfully!")
}

func RunBreaking(ctx context.Context, client *github.Client, owner string) {
	executeScenario(ctx, client, owner, "Breaking Change",
		defaultSubstrateYaml(), defaultOpenAPIYaml(),
		defaultSubstrateYaml(), removedEndpointYaml(),
		"❌ BREAKING")
}

func RunSafe(ctx context.Context, client *github.Client, owner string) {
	executeScenario(ctx, client, owner, "Safe Extension",
		defaultSubstrateYaml(), defaultOpenAPIYaml(),
		defaultSubstrateYaml(), addedEndpointYaml(),
		"✅ Safe")
}

func RunOverride(ctx context.Context, client *github.Client, owner string) {
	executeScenario(ctx, client, owner, "Config Override",
		defaultSubstrateYaml(), defaultOpenAPIYaml(),
		overrideSubstrateYaml(), removedEndpointYaml(),
		"✅ Acknowledged")
}

func RunWarning(ctx context.Context, client *github.Client, owner string) {
	executeScenario(ctx, client, owner, "Warnings Only",
		defaultSubstrateYaml(), defaultOpenAPIYaml(),
		defaultSubstrateYaml(), deprecatedEndpointYaml(),
		"🟡 WARNING")
}

func executeScenario(ctx context.Context, client *github.Client, owner, scenarioName, baseConfig, baseSchema, prConfig, prSchema, expectedStatus string) {
	log.Printf("=== Running Scenario: %s ===", scenarioName)

	log.Println("Seeding the main branch with baseline files...")
	helpers.SeedFile(ctx, client, owner, providerRepoName, "substrate.yaml", "main", baseConfig)
	helpers.SeedFile(ctx, client, owner, providerRepoName, "openapi.yaml", "main", baseSchema)
	
	log.Println("Waiting 5s for the Registry API to sync baselines...")
	time.Sleep(5 * time.Second)

	branchName := fmt.Sprintf("e2e-openapi-%d", time.Now().Unix())

	log.Printf("Creating branch %s...", branchName)
	ref, _, err := client.Git.GetRef(ctx, owner, providerRepoName, "refs/heads/main")
	if err != nil { log.Fatalf("Failed to get main ref: %v", err) }

	_, _, err = client.Git.CreateRef(ctx, owner, providerRepoName, &github.Reference{
		Ref: github.String("refs/heads/" + branchName),
		Object: &github.GitObject{ SHA: ref.Object.SHA },
	})
	if err != nil { log.Fatalf("Failed to create branch: %v", err) }

	log.Println("Pushing PR changes...")
	helpers.SeedFile(ctx, client, owner, providerRepoName, "substrate.yaml", branchName, prConfig)
	helpers.SeedFile(ctx, client, owner, providerRepoName, "openapi.yaml", branchName, prSchema)

	log.Println("Opening Pull Request...")
	pr, _, err := client.PullRequests.Create(ctx, owner, providerRepoName, &github.NewPullRequest{
		Title: github.String(fmt.Sprintf("Automated E2E: %s", scenarioName)),
		Head:  github.String(branchName),
		Base:  github.String("main"),
		Body:  github.String("Automated test generated by Substrate E2E suite."),
	})
	if err != nil { log.Fatalf("Failed to create PR: %v", err) }
	log.Printf("Created PR: %s", pr.GetHTMLURL())

	log.Println("Polling for Substrate PR comment (waiting up to 60s)...")
	var foundComment *github.IssueComment
	for i := 0; i < 20; i++ {
		time.Sleep(3 * time.Second)
		comments, _, err := client.Issues.ListComments(ctx, owner, providerRepoName, pr.GetNumber(), nil)
		if err != nil { continue }
		for _, comment := range comments {
			if strings.Contains(comment.GetBody(), "Substrate") {
				// Only match if the expected status is found
				if strings.Contains(comment.GetBody(), expectedStatus) {
					foundComment = comment
					break
				}
			}
		}
		if foundComment != nil { break }
	}

	if foundComment == nil {
		log.Fatalf("❌ FAILED: Substrate bot did not post '%s' comment within 60 seconds.", expectedStatus)
	} else {
		log.Printf("✅ SUCCESS: Found expected status '%s'!", expectedStatus)
	}

	log.Println("Cleaning up PR and branch...")
	_, _, _ = client.PullRequests.Edit(ctx, owner, providerRepoName, pr.GetNumber(), &github.PullRequest{State: github.String("closed")})
	_, _ = client.Git.DeleteRef(ctx, owner, providerRepoName, "refs/heads/"+branchName)
}

func defaultSubstrateYaml() string {
	return `service: test-provider-api
schema_type: openapi
spec_path: openapi.yaml
`
}

func overrideSubstrateYaml() string {
	return `service: test-provider-api
schema_type: openapi
spec_path: openapi.yaml

overrides:
  - rule_id: ENDPOINT_REMOVED
    path: paths./users/{id}
    reason: "E2E testing override functionality"
`
}

func defaultOpenAPIYaml() string {
	return `openapi: "3.0.0"
info:
  title: Provider API
  version: "1.0.0"
paths:
  /users:
    get:
      summary: List users
      responses:
        "200":
          description: OK
  /users/{id}:
    get:
      summary: Get user by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
`
}

func removedEndpointYaml() string {
	return `openapi: "3.0.0"
info:
  title: Provider API
  version: "1.0.0"
paths:
  /users:
    get:
      summary: List users
      responses:
        "200":
          description: OK
`
}

func addedEndpointYaml() string {
	return `openapi: "3.0.0"
info:
  title: Provider API
  version: "1.0.0"
paths:
  /users:
    get:
      summary: List users
      responses:
        "200":
          description: OK
  /users/{id}:
    get:
      summary: Get user by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
  /health:
    get:
      summary: Health check
      responses:
        "200":
          description: OK
`
}

func deprecatedEndpointYaml() string {
	return `openapi: "3.0.0"
info:
  title: Provider API
  version: "1.0.0"
paths:
  /users:
    get:
      summary: List users
      responses:
        "200":
          description: OK
  /users/{id}:
    get:
      summary: Get user by ID
      deprecated: true
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
`
}
