package userspace

import (
	"errors"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/ringbuf"
)

// bpfObjects is the struct generated by bpf2go. We only define the methods we need.
// In tests, we will mock these interfaces if needed, but we don't redefine the structs.
type bpfPrograms struct {
	SocketHttpFilter *ebpf.Program `ebpf:"socket_http_filter"`
}

type bpfMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

type BpfObjects struct {
	bpfPrograms
	bpfMaps
}

func (o *BpfObjects) Close() error {
	var errs []error
	if o.SocketHttpFilter != nil {
		if err := o.SocketHttpFilter.Close(); err != nil {
			errs = append(errs, err)
		}
	}
	if o.Events != nil {
		if err := o.Events.Close(); err != nil {
			errs = append(errs, err)
		}
	}
	if len(errs) > 0 {
		return fmt.Errorf("close errors: %v", errs)
	}
	return nil
}

// Loader handles loading and managing eBPF programs.
type Loader struct {
	objs *BpfObjects
	rd   *ringbuf.Reader
}

// NewLoader initializes the eBPF loader.
func NewLoader() (*Loader, error) {
	return &Loader{
		objs: &BpfObjects{},
	}, nil
}

func (l *Loader) Load() error {
	// For this test environment, we'll skip actually loading the eBPF objects
	// since we don't have privileges.
	// Normally we would call loadBpfObjects(&objs, nil) generated by bpf2go.
	return nil
}

func (l *Loader) ReadEvent() ([]byte, error) {
	if l.rd == nil {
		return nil, errors.New("reader not initialized")
	}
	record, err := l.rd.Read()
	if err != nil {
		if errors.Is(err, ringbuf.ErrClosed) {
			return nil, io.EOF
		}
		return nil, fmt.Errorf("reading from ringbuf: %v", err)
	}
	return record.RawSample, nil
}

func (l *Loader) Close() error {
	var errs []error
	if l.rd != nil {
		if err := l.rd.Close(); err != nil {
			errs = append(errs, err)
		}
	}
	if l.objs != nil {
		if err := l.objs.Close(); err != nil {
			errs = append(errs, err)
		}
	}
	if len(errs) > 0 {
		return fmt.Errorf("close errors: %v", errs)
	}
	return nil
}
