package handlers

import (
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/KrushnaVardhanReddy/substrate/api/internal/db"
	"github.com/KrushnaVardhanReddy/substrate/api/internal/github"
	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"
)

type OTelMetricsSpan struct {
	RepoID    uuid.UUID `json:"repo_id"`
	Method    string    `json:"method"`
	Path      string    `json:"path"`
	Timestamp time.Time `json:"timestamp"`
}

func OTelMetricsHandler(store db.Store) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var spans []OTelMetricsSpan
		if err := json.NewDecoder(r.Body).Decode(&spans); err != nil {
			http.Error(w, "invalid request body", http.StatusBadRequest)
			return
		}

		ctx := r.Context()
		for _, span := range spans {
			if err := store.UpsertEndpointTraffic(ctx, span.RepoID, span.Method, span.Path, span.Timestamp); err != nil {
				http.Error(w, "internal server error", http.StatusInternalServerError)
				return
			}
		}

		w.WriteHeader(http.StatusAccepted)
		json.NewEncoder(w).Encode(map[string]string{"status": "accepted"})
	}
}

func GetZombiesHandler(store db.Store) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		orgName := chi.URLParam(r, "org")
		if orgName == "" {
			http.Error(w, "missing org parameter", http.StatusBadRequest)
			return
		}

		// 30 days threshold
		since := time.Now().Add(-30 * 24 * time.Hour)
		zombies, err := store.GetZeroTrafficEndpoints(r.Context(), orgName, since)
		if err != nil {
			http.Error(w, "failed to get zombies", http.StatusInternalServerError)
			return
		}

		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(zombies)
	}
}

type ZombiePRRequest struct {
	RepoName string `json:"repo_name"`
	Method   string `json:"method"`
	Path     string `json:"path"`
}

func CreateZombiePRHandler(ghClient github.Client) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		orgName := chi.URLParam(r, "org")
		if orgName == "" {
			http.Error(w, "missing org parameter", http.StatusBadRequest)
			return
		}

		var req ZombiePRRequest
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			http.Error(w, "invalid request body", http.StatusBadRequest)
			return
		}

		ctx := r.Context()

		specPath, err := ghClient.SearchCode(ctx, orgName, req.RepoName, "openapi")
		if err != nil || specPath == "" {
			specPath = "openapi.yaml"
		}

		_, err = ghClient.GetFileContent(ctx, orgName, req.RepoName, specPath)
		if err != nil {
			http.Error(w, "failed to fetch spec content", http.StatusInternalServerError)
			return
		}

		diffPatch := fmt.Sprintf("--- %s\n+++ %s\n@@ -1,3 +1,3 @@\n-  %s:\n-    %s:", specPath, specPath, req.Path, strings.ToLower(req.Method))

		title := fmt.Sprintf("chore(api): Prune zombie endpoint %s %s", req.Method, req.Path)
		body := "This PR was automatically generated by Substrate to prune an endpoint that has received zero traffic in the last 30 days."

		branchName := fmt.Sprintf("substrate/prune-zombie-%d", time.Now().Unix())
		prURL, err := ghClient.CreateDraftPR(ctx, orgName, req.RepoName, branchName, diffPatch, title, body)
		if err != nil {
			http.Error(w, "failed to create PR", http.StatusInternalServerError)
			return
		}

		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(map[string]string{"pr_url": prURL})
	}
}
