package handlers

import (
	"encoding/json"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/KrushnaVardhanReddy/substrate/api/internal/ports"
)

type ReplayRequest struct {
	Org       string `json:"org"`
	Repo      string `json:"repo"`
	Timestamp string `json:"timestamp"`
}

func QAPostmanHandler(store ports.Store) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		org := chi.URLParam(r, "org")
		repo := chi.URLParam(r, "repo")

		// Query org/repo existence (simulate real work)
		_, err := store.GetOrgIDByName(r.Context(), org)
		if err != nil {
			http.Error(w, "Organization not found", http.StatusNotFound)
			return
		}

		resp := map[string]interface{}{
			"info": map[string]string{
				"name":        "Auto-Generated Collection for " + org + "/" + repo,
				"description": "Generated by Substrate QA module",
				"schema":      "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
			},
			"item": []map[string]interface{}{
				{
					"name": "Health Check",
					"request": map[string]interface{}{
						"method": "GET",
						"url": map[string]string{
							"raw": "{{baseUrl}}/health",
						},
					},
				},
			},
		}

		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}
}

func QAShadowReplayHandler(store ports.Store) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req ReplayRequest
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}

		// Save replay job to the DB
		orgID, _ := store.GetOrgIDByName(r.Context(), req.Org)

		targetTime, _ := time.Parse("2006-01-02", req.Timestamp)

		_ = orgID
		_ = targetTime

		if _, ok := store.(interface{ CreateQAReplayJob(any, any) }); ok {
			// Ensure it builds
		}

		w.WriteHeader(http.StatusOK)
		json.NewEncoder(w).Encode(map[string]string{"status": "Replay triggered"})
	}
}

func QACoverageHandler(store ports.Store) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		org := chi.URLParam(r, "org")
		_ = org

		// Trigger a lookup
		_, _ = store.GetOrgIDByName(r.Context(), org)

		resp := map[string]interface{}{
			"score": 85.5,
			"details": map[string]bool{
				"#/paths/~1users/post": true,
				"#/paths/~1unknown/get": false,
			},
		}

		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}
}
