package sql

import (
	"context"
	"fmt"
	"log"
	"strings"
	"time"

	"e2e/helpers"

	"github.com/google/go-github/v62/github"
)

const (
	providerRepoName = "substrate-test-provider"
	consumerRepoName = "substrate-test-consumer"
)

func RunAll(ctx context.Context, client *github.Client, owner string) {
	log.Println("Starting SQL Automated Test Suite...")
	RunBreaking(ctx, client, owner)
	RunSafe(ctx, client, owner)
	RunOverride(ctx, client, owner)
	RunWarning(ctx, client, owner)
	log.Println("🎉 All SQL Scenarios Completed Successfully!")
}

func RunBreaking(ctx context.Context, client *github.Client, owner string) {
	executeScenario(ctx, client, owner, "SQL Breaking Change",
		defaultSubstrateYaml(), defaultSQL(),
		defaultSubstrateYaml(), removedColumnSQL(),
		"BREAKING")
}

func RunSafe(ctx context.Context, client *github.Client, owner string) {
	executeScenario(ctx, client, owner, "SQL Safe Extension",
		defaultSubstrateYaml(), defaultSQL(),
		defaultSubstrateYaml(), addedNullableColumnSQL(),
		"All Clear")
}

func RunOverride(ctx context.Context, client *github.Client, owner string) {
	executeScenario(ctx, client, owner, "SQL Config Override",
		defaultSubstrateYaml(), defaultSQL(),
		overrideSubstrateYaml(), removedColumnSQL(),
		"All Clear")
}

func RunWarning(ctx context.Context, client *github.Client, owner string) {
	executeScenario(ctx, client, owner, "SQL Warnings Only",
		defaultSubstrateYaml(), defaultSQL(),
		defaultSubstrateYaml(), changedDefaultSQL(),
		"🟡 WARNING")
}

func executeScenario(ctx context.Context, client *github.Client, owner, scenarioName, baseConfig, baseSchema, prConfig, prSchema, expectedStatus string) {
	log.Printf("=== Running Scenario: %s ===", scenarioName)

	log.Println("Seeding the main branch with baseline files...")
	helpers.SeedFile(ctx, client, owner, providerRepoName, "substrate.yaml", "main", baseConfig)
	helpers.SeedFile(ctx, client, owner, providerRepoName, "schema.sql", "main", baseSchema)

	consumerConfig := fmt.Sprintf(`# Seeded at %d
service: test-consumer
consumers:
  - name: sql-dep
    provider_repo: %s/%s
    schema_type: sql
    provider_spec_path: schema.sql
`, time.Now().UnixNano(), owner, providerRepoName)
	helpers.SeedFile(ctx, client, owner, consumerRepoName, "substrate.yaml", "main", consumerConfig)
	
	log.Println("Waiting 15s for the Registry API to sync baselines...")
	time.Sleep(15 * time.Second)

	branchName := fmt.Sprintf("e2e-sql-%d", time.Now().Unix())

	log.Printf("Creating branch %s...", branchName)
	ref, _, err := client.Git.GetRef(ctx, owner, providerRepoName, "refs/heads/main")
	if err != nil { log.Fatalf("Failed to get main ref: %v", err) }

	_, _, err = client.Git.CreateRef(ctx, owner, providerRepoName, &github.Reference{
		Ref: github.String("refs/heads/" + branchName),
		Object: &github.GitObject{ SHA: ref.Object.SHA },
	})
	if err != nil { log.Fatalf("Failed to create branch: %v", err) }

	log.Println("Pushing PR changes...")
	helpers.SeedFile(ctx, client, owner, providerRepoName, "substrate.yaml", branchName, prConfig)
	helpers.SeedFile(ctx, client, owner, providerRepoName, "schema.sql", branchName, prSchema)

	log.Println("Opening Pull Request...")
	pr, _, err := client.PullRequests.Create(ctx, owner, providerRepoName, &github.NewPullRequest{
		Title: github.String(fmt.Sprintf("Automated E2E: %s", scenarioName)),
		Head:  github.String(branchName),
		Base:  github.String("main"),
		Body:  github.String("Automated test generated by Substrate E2E suite."),
	})
	if err != nil { log.Fatalf("Failed to create PR: %v", err) }
	log.Printf("Created PR: %s", pr.GetHTMLURL())

	log.Println("Polling for Substrate PR comment (waiting up to 60s)...")
	var foundComment *github.IssueComment
	for i := 0; i < 20; i++ {
		time.Sleep(3 * time.Second)
		comments, _, err := client.Issues.ListComments(ctx, owner, providerRepoName, pr.GetNumber(), nil)
		if err != nil { continue }
		for _, comment := range comments {
			if strings.Contains(comment.GetBody(), "Substrate") {
				if strings.Contains(comment.GetBody(), expectedStatus) {
					foundComment = comment
					break
				}
			}
		}
		if foundComment != nil { break }
	}

	if foundComment == nil {
		log.Fatalf("❌ FAILED: Substrate bot did not post '%s' comment within 60 seconds.", expectedStatus)
	} else {
		log.Printf("✅ SUCCESS: Found expected status '%s'!", expectedStatus)
	}

	log.Println("Cleaning up PR and branch...")
	_, _, _ = client.PullRequests.Edit(ctx, owner, providerRepoName, pr.GetNumber(), &github.PullRequest{State: github.String("closed")})
	_, _ = client.Git.DeleteRef(ctx, owner, providerRepoName, "refs/heads/"+branchName)
}

func defaultSubstrateYaml() string {
	return `service: test-provider-sql
schema_type: sql
spec_path: schema.sql
`
}

func overrideSubstrateYaml() string {
	return `service: test-provider-sql
schema_type: sql
spec_path: schema.sql

overrides:
  - rule_id: COLUMN_REMOVED
    path: tables.users.columns.email
    reason: "E2E testing SQL override functionality"
    approved_by: "e2e-bot@example.com"
    expires: "2099-12-31"
`
}

func defaultSQL() string {
	return `
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL DEFAULT 'unknown@example.com'
);
`
}

func removedColumnSQL() string {
	return `
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);
`
}

func addedNullableColumnSQL() string {
	return `
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL DEFAULT 'unknown@example.com',
    age INTEGER
);
`
}

func changedDefaultSQL() string {
	return `
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL
);
`
}
