// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Krushna Vardhan Reddy. All rights reserved.
// Part of the Substrate diff engine — open-source under the MIT License.
// See engine/LICENSE for details.

package ai

import (
	"context"
	"fmt"
	"strings"

	"github.com/sashabaranov/go-openai"
)

// GitHubClient is a minimal interface needed to create the fix PR.
type GitHubClient interface {
	CreateDraftPR(ctx context.Context, owner, repo, branch, patch, title, body string) (string, error)
}

// LLMClient is a minimal interface for chatting with the LLM (for testability).
type LLMClient interface {
	CreateChatCompletion(ctx context.Context, request openai.ChatCompletionRequest) (openai.ChatCompletionResponse, error)
}

type AgentConsumer struct {
	RepoName string
	Owner    string
}

type AgentRegistryClient interface {
	GetAgentsByTool(ctx context.Context, toolName string) ([]AgentConsumer, error)
}

// FixAgentsForTool generates an updated JSON schema/prompt for a broken tool parameter
// for all agents that depend on it, and opens PRs in their repos.
func FixAgentsForTool(
	ctx context.Context,
	llmClient LLMClient,
	githubClient GitHubClient,
	registry AgentRegistryClient,
	toolName string,
	brokenChanges string,
) error {
	agents, err := registry.GetAgentsByTool(ctx, toolName)
	if err != nil {
		return fmt.Errorf("failed to get agents for tool %s: %w", toolName, err)
	}

	for _, agent := range agents {
		_, err := GenerateAgentFixPR(ctx, llmClient, githubClient, agent.RepoName, agent.Owner, toolName, brokenChanges)
		if err != nil {
			// Log error but continue with other agents
			fmt.Printf("failed to generate fix PR for agent %s/%s: %v\n", agent.Owner, agent.RepoName, err)
		}
	}

	return nil
}

// GenerateAgentFixPR generates an updated JSON schema/prompt for a broken tool parameter
// and opens a PR in the consumer's agent repo.
func GenerateAgentFixPR(
	ctx context.Context,
	llmClient LLMClient,
	githubClient GitHubClient,
	agentRepo string,
	agentOwner string,
	toolName string,
	brokenChanges string,
) (string, error) {
	systemPrompt := fmt.Sprintf(`You are the Substrate AI Agent Fixer.
An upstream API tool '%s' that this agent depends on has introduced breaking changes:
%s

Generate a patch (diff) that updates the agent's tool-calling schema or prompt to accommodate these changes.
Your response MUST be ONLY the raw diff. Do not include markdown formatting or explanation.`, toolName, brokenChanges)

	req := openai.ChatCompletionRequest{
		Model: openai.GPT4o,
		Messages: []openai.ChatCompletionMessage{
			{
				Role:    openai.ChatMessageRoleSystem,
				Content: systemPrompt,
			},
			{
				Role:    openai.ChatMessageRoleUser,
				Content: "Please generate the patch.",
			},
		},
	}

	resp, err := llmClient.CreateChatCompletion(ctx, req)
	if err != nil {
		return "", fmt.Errorf("failed to generate fix from LLM: %w", err)
	}

	patch := strings.TrimSpace(resp.Choices[0].Message.Content)
	// simple cleanup if it returned markdown
	if strings.HasPrefix(patch, "```diff") {
		patch = strings.TrimPrefix(patch, "```diff")
		patch = strings.TrimSuffix(patch, "```")
		patch = strings.TrimSpace(patch)
	}

	branchName := fmt.Sprintf("substrate/fix-agent-tool-%s", toolName)
	title := fmt.Sprintf("fix(agent): update tool schema for %s breaking changes", toolName)
	body := fmt.Sprintf("This is an automated PR generated by Substrate AI Agent Registry.\n\nThe upstream API introduced breaking changes to the tool `%s`:\n\n```\n%s\n```", toolName, brokenChanges)

	prURL, err := githubClient.CreateDraftPR(ctx, agentOwner, agentRepo, branchName, patch, title, body)
	if err != nil {
		return "", fmt.Errorf("failed to create PR: %w", err)
	}

	return prURL, nil
}
