apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "substrate.fullname" . }}
  labels:
    {{- include "substrate.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "substrate.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "substrate.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "substrate.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DATABASE_URL
              value: {{ .Values.env.SUBSTRATE_DB_URL | quote }}
            - name: GITHUB_APP_ID
              value: {{ .Values.env.GITHUB_APP_ID | quote }}
            - name: GITHUB_CLIENT_ID
              value: {{ .Values.env.GITHUB_CLIENT_ID | quote }}
            - name: GITHUB_CLIENT_SECRET
              value: {{ .Values.env.GITHUB_CLIENT_SECRET | quote }}
            - name: JWT_SECRET
              value: {{ .Values.env.JWT_SECRET | quote }}
            - name: REGISTRY_API_TOKEN
              value: {{ .Values.env.REGISTRY_API_TOKEN | quote }}
            - name: DASHBOARD_URL
              value: {{ .Values.env.DASHBOARD_URL | quote }}
          ports:
            - name: http
              containerPort: 8090
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
# API Deployment
