package mockgen

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/KrushnaVardhanReddy/substrate/engine/internal/diff"
	"github.com/KrushnaVardhanReddy/substrate/engine/internal/report"
	"github.com/KrushnaVardhanReddy/substrate/engine/pkg/ai"
	"github.com/go-git/go-git/v5"
	"github.com/go-git/go-git/v5/plumbing/object"
	"github.com/sashabaranov/go-openai"
)

// DiscoverFixtures scans the given repository directory for .json files
// located in `__fixtures__` or `testdata/` directories.
func DiscoverFixtures(repoDir string) ([]string, error) {
	var fixtures []string

	err := filepath.Walk(repoDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		if info.IsDir() {
			return nil
		}

		if !strings.HasSuffix(info.Name(), ".json") {
			return nil
		}

		// Check if it's inside a `__fixtures__` or `testdata` directory.
		dir := filepath.Dir(path)
		parts := strings.Split(filepath.ToSlash(dir), "/")

		isFixtureDir := false
		for _, part := range parts {
			if part == "__fixtures__" || part == "testdata" {
				isFixtureDir = true
				break
			}
		}

		if isFixtureDir {
			fixtures = append(fixtures, path)
		}

		return nil
	})

	if err != nil {
		return nil, err
	}

	return fixtures, nil
}

// UpdateFixture takes an AIClient, a DiffReport (mismatches), and the current JSON fixture,
// and asks the LLM to update the mock data.
func UpdateFixture(ctx context.Context, client ai.AIClient, diffReport *report.DiffReport, fixtureContent []byte) ([]byte, error) {
	diffBytes, err := json.MarshalIndent(diffReport, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("failed to marshal diff report: %w", err)
	}

	systemPrompt := "You are a QA mock data generator for Substrate. " +
		"The upstream API schema has changed. You will be provided with a JSON DiffReport of the changes " +
		"and the current JSON fixture file. " +
		"Your task is to update the JSON fixture so that it is valid against the new schema. " +
		"You must return ONLY the valid JSON block containing the updated fixture. " +
		"Do not include any other text, explanation, or conversational filler."

	userPrompt := fmt.Sprintf("DiffReport:\n%s\n\nCurrent Fixture JSON:\n%s", string(diffBytes), string(fixtureContent))

	req := openai.ChatCompletionRequest{
		Model: openai.GPT4o,
		Messages: []openai.ChatCompletionMessage{
			{
				Role:    openai.ChatMessageRoleSystem,
				Content: systemPrompt,
			},
			{
				Role:    openai.ChatMessageRoleUser,
				Content: userPrompt,
			},
		},
		Stream: true,
	}

	stream, err := client.CreateChatCompletionStream(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to create chat completion stream: %w", err)
	}
	defer stream.Close()

	var fullResponse strings.Builder
	for {
		chunk, err := stream.Recv()
		if errors.Is(err, io.EOF) {
			break
		}
		if err != nil {
			return nil, fmt.Errorf("stream error: %w", err)
		}
		fullResponse.WriteString(chunk)
	}

	extractedJSON := extractJSON(fullResponse.String())
	return []byte(extractedJSON), nil
}

func extractJSON(response string) string {
	text := strings.TrimSpace(response)
	if strings.HasPrefix(text, "```json") {
		text = strings.TrimPrefix(text, "```json")
	} else if strings.HasPrefix(text, "```") {
		text = strings.TrimPrefix(text, "```")
	}

	if strings.HasSuffix(text, "```") {
		text = strings.TrimSuffix(text, "```")
	}

	return strings.TrimSpace(text)
}

// CreatePR commits modifications in repoDir, creates a branch, and opens a GitHub PR.
func CreatePR(ctx context.Context, repoDir, branchName, repoOwner, repoName, token string) error {
	r, err := git.PlainOpen(repoDir)
	if err != nil {
		return fmt.Errorf("failed to open repo: %w", err)
	}

	w, err := r.Worktree()
	if err != nil {
		return fmt.Errorf("failed to get worktree: %w", err)
	}

	status, err := w.Status()
	if err != nil {
		return fmt.Errorf("failed to get status: %w", err)
	}

	if status.IsClean() {
		// Nothing to commit
		return nil
	}

	_, err = w.Add(".")
	if err != nil {
		return fmt.Errorf("failed to add files: %w", err)
	}

	commit, err := w.Commit("test: auto-update mock fixtures", &git.CommitOptions{
		Author: &object.Signature{
			Name:  "Substrate AI",
			Email: "ai@substrate.local",
			When:  time.Now(),
		},
	})
	if err != nil {
		return fmt.Errorf("failed to commit: %w", err)
	}
	_ = commit // Used successfully

	if token == "" || repoOwner == "" || repoName == "" {
		// Just stop here if no token provided
		return nil
	}

	prPayload := map[string]string{
		"title": "Update mock fixtures to match new schema",
		"body":  "Auto-generated by Substrate AI mock generator.",
		"head":  branchName,
		"base":  "main",
	}

	payloadBytes, _ := json.Marshal(prPayload)
	reqUrl := fmt.Sprintf("https://api.github.com/repos/%s/%s/pulls", repoOwner, repoName)
	req, err := http.NewRequestWithContext(ctx, "POST", reqUrl, bytes.NewReader(payloadBytes))
	if err != nil {
		return err
	}

	req.Header.Set("Authorization", "Bearer "+token)
	req.Header.Set("Accept", "application/vnd.github.v3+json")

	httpClient := &http.Client{}
	resp, err := httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("failed to create PR: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return fmt.Errorf("github API error: status %d", resp.StatusCode)
	}

	return nil
}

// RunMockGenerator is the main entry point to scan fixtures, diff schemas, call AI, and open a PR.
func RunMockGenerator(ctx context.Context, repoDir, oldSchemaPath, newSchemaPath, repoOwner, repoName, token, branchName string) error {
	diffReport, err := diff.CompareOpenAPI(oldSchemaPath, newSchemaPath, true, nil)
	if err != nil {
		return fmt.Errorf("failed to compare schema: %w", err)
	}

	fixtures, err := DiscoverFixtures(repoDir)
	if err != nil {
		return fmt.Errorf("failed to discover fixtures: %w", err)
	}

	aiClient, err := ai.NewAIClient()
	if err != nil {
		return fmt.Errorf("failed to create AI client: %w", err)
	}

	for _, fixturePath := range fixtures {
		content, err := os.ReadFile(fixturePath)
		if err != nil {
			continue
		}

		updatedContent, err := UpdateFixture(ctx, aiClient, diffReport, content)
		if err != nil {
			continue
		}

		if err := os.WriteFile(fixturePath, updatedContent, 0644); err != nil {
			return fmt.Errorf("failed to write updated fixture to %s: %w", fixturePath, err)
		}
	}

	return CreatePR(ctx, repoDir, branchName, repoOwner, repoName, token)
}
