package aiml

import (
	"context"
	"fmt"
	"log"
	"strings"
	"time"

	"e2e/helpers"
	"github.com/google/go-github/v62/github"
)

const providerRepoName = "substrate-test-provider"
const consumerRepoName = "substrate-test-consumer"

func RunAll(ctx context.Context, client *github.Client, owner string) {
	log.Println("Starting AI/ML Automated Test Suite...")
	RunBreaking(ctx, client, owner)
	RunSafe(ctx, client, owner)
	RunOverride(ctx, client, owner)
}

func RunSafe(ctx context.Context, client *github.Client, owner string) {
	executeScenario(ctx, client, owner, "AI/ML Safe Extension",
		defaultSubstrateYaml(), defaultSchema(),
		defaultSubstrateYaml(), safeSchema(),
		"All Clear", "")
}

func RunBreaking(ctx context.Context, client *github.Client, owner string) {
	executeScenario(ctx, client, owner, "AI/ML Breaking Change",
		defaultSubstrateYaml(), defaultSchema(),
		defaultSubstrateYaml(), breakingSchema(),
		"BREAKING", "AIML_INPUT_TYPE_CHANGED")
}

func RunOverride(ctx context.Context, client *github.Client, owner string) {
	executeScenario(ctx, client, owner, "AI/ML Config Override",
		defaultSubstrateYaml(), defaultSchema(),
		overrideSubstrateYaml(), breakingSchema(),
		"All Clear", "")
}

func executeScenario(ctx context.Context, client *github.Client, owner, scenarioName, baseConfig, baseSchema, prConfig, prSchema, expectedStatus, expectedRule string) {
	log.Printf("=== Running Scenario: %s ===", scenarioName)

	log.Println("Seeding the main branch with baseline files...")
	helpers.SeedFile(ctx, client, owner, providerRepoName, "substrate.yaml", "main", baseConfig)
	helpers.SeedFile(ctx, client, owner, providerRepoName, "model.yaml", "main", baseSchema)

	consumerConfig := fmt.Sprintf(`service: test-consumer
consumers:
  - name: "test-provider"
    type: ai-model
    source: "github.com/%s/%s"
    path: "model.yaml"
    branch: "main"`, owner, providerRepoName)

	helpers.SeedFile(ctx, client, owner, consumerRepoName, "substrate.yaml", "main", consumerConfig)
	helpers.SeedFile(ctx, client, owner, consumerRepoName, "model.yaml", "main", baseSchema)

	log.Println("Waiting 15s for the Registry API to sync baselines...")
	time.Sleep(15 * time.Second)

	prBranch := fmt.Sprintf("e2e-aiml-%d", time.Now().Unix())
	log.Printf("Creating branch %s...", prBranch)
	ref, _, err := client.Git.GetRef(ctx, owner, providerRepoName, "refs/heads/main")
	if err != nil {
		log.Fatalf("Failed to get main ref: %v", err)
	}

	_, _, err = client.Git.CreateRef(ctx, owner, providerRepoName, &github.Reference{
		Ref:    github.String("refs/heads/" + prBranch),
		Object: &github.GitObject{SHA: ref.Object.SHA},
	})
	if err != nil {
		log.Fatalf("Failed to create branch: %v", err)
	}

	log.Println("Pushing PR changes...")
	helpers.SeedFile(ctx, client, owner, providerRepoName, "substrate.yaml", prBranch, prConfig)
	helpers.SeedFile(ctx, client, owner, providerRepoName, "model.yaml", prBranch, prSchema)

	log.Println("Opening Pull Request...")
	pr, _, err := client.PullRequests.Create(ctx, owner, providerRepoName, &github.NewPullRequest{
		Title: github.String(fmt.Sprintf("Automated E2E: %s", scenarioName)),
		Head:  github.String(prBranch),
		Base:  github.String("main"),
		Body:  github.String("Automated test generated by Substrate E2E suite."),
	})
	if err != nil {
		log.Fatalf("Failed to create PR: %v", err)
	}
	log.Printf("Created PR: %s", pr.GetHTMLURL())

	log.Println("Polling for Substrate PR comment (waiting up to 60s)...")
	var foundComment *github.IssueComment
	for i := 0; i < 20; i++ {
		time.Sleep(3 * time.Second)
		comments, _, err := client.Issues.ListComments(ctx, owner, providerRepoName, pr.GetNumber(), nil)
		if err != nil {
			log.Fatalf("❌ FAILED: Could not list PR comments: %v", err)
		}

		for _, comment := range comments {
			if strings.Contains(comment.GetBody(), "Substrate") {
				if strings.Contains(comment.GetBody(), expectedStatus) {
					if expectedRule == "" || strings.Contains(comment.GetBody(), expectedRule) {
						foundComment = comment
						break
					}
				}
			}
		}
		if foundComment != nil {
			break
		}
	}

	if foundComment == nil {
		if expectedRule != "" {
			log.Fatalf("❌ FAILED: Substrate bot did not post '%s' comment with rule '%s' within 60 seconds.", expectedStatus, expectedRule)
		} else {
			log.Fatalf("❌ FAILED: Substrate bot did not post '%s' comment within 60 seconds.", expectedStatus)
		}
	} else {
		if expectedRule != "" {
			log.Printf("✅ SUCCESS: Found expected status '%s' and asserted rule '%s'!", expectedStatus, expectedRule)
		} else {
			log.Printf("✅ SUCCESS: Found expected status '%s'!", expectedStatus)
		}
	}

	log.Println("Cleaning up PR and branch...")
	_, _, _ = client.PullRequests.Edit(ctx, owner, providerRepoName, pr.GetNumber(), &github.PullRequest{State: github.String("closed")})
	_, _ = client.Git.DeleteRef(ctx, owner, providerRepoName, "refs/heads/"+prBranch)
}

func defaultSubstrateYaml() string {
	return `service: test-provider-aiml
schema_type: ai-model
spec_path: model.yaml
`
}

func overrideSubstrateYaml() string {
	return `service: test-provider-aiml
schema_type: ai-model
spec_path: model.yaml

overrides:
  - rule_id: AIML_INPUT_TYPE_CHANGED
    path: ml_model.inputs.image.type
    reason: "E2E testing AIML override functionality"
    approved_by: "e2e-bot@example.com"
    expires: "2099-12-31"
`
}

func defaultSchema() string {
	return `service: test-provider-aiml
ml_model:
  name: "image-classifier"
  version: "1.0.0"
  framework: "tensorflow"
  task: "image_classification"
  inputs:
    - name: "image"
      type: "tensor[float32, 224, 224, 3]"
      required: true
  outputs:
    - name: "probabilities"
      type: "tensor[float32, 1000]"
      required: true
`
}

func safeSchema() string {
	return `service: test-provider-aiml
ml_model:
  name: "image-classifier"
  version: "1.0.0"
  framework: "tensorflow"
  task: "image_classification"
  inputs:
    - name: "image"
      type: "tensor[float32, 224, 224, 3]"
      required: true
    - name: "threshold"
      type: "float"
      required: false
  outputs:
    - name: "probabilities"
      type: "tensor[float32, 1000]"
      required: true
`
}

func breakingSchema() string {
	return `service: test-provider-aiml
ml_model:
  name: "image-classifier"
  version: "1.0.0"
  framework: "tensorflow"
  task: "image_classification"
  inputs:
    - name: "image"
      type: "tensor[float32, 256, 256, 3]"
      required: true
  outputs:
    - name: "probabilities"
      type: "tensor[float32, 1000]"
      required: true
`
}
