// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: airbyte.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAirbyteSource = `-- name: DeleteAirbyteSource :exec
DELETE FROM airbyte_sources
WHERE org = $1 AND id = $2
`

type DeleteAirbyteSourceParams struct {
	Org string
	ID  pgtype.UUID
}

func (q *Queries) DeleteAirbyteSource(ctx context.Context, arg DeleteAirbyteSourceParams) error {
	_, err := q.db.Exec(ctx, deleteAirbyteSource, arg.Org, arg.ID)
	return err
}

const getAirbyteSource = `-- name: GetAirbyteSource :one
SELECT id, org, name, connector, config_enc, created_at, updated_at
FROM airbyte_sources
WHERE org = $1 AND connector = $2
`

type GetAirbyteSourceParams struct {
	Org       string
	Connector string
}

func (q *Queries) GetAirbyteSource(ctx context.Context, arg GetAirbyteSourceParams) (AirbyteSource, error) {
	row := q.db.QueryRow(ctx, getAirbyteSource, arg.Org, arg.Connector)
	var i AirbyteSource
	err := row.Scan(
		&i.ID,
		&i.Org,
		&i.Name,
		&i.Connector,
		&i.ConfigEnc,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAirbyteSourceByID = `-- name: GetAirbyteSourceByID :one
SELECT id, org, name, connector, config_enc, created_at, updated_at
FROM airbyte_sources
WHERE org = $1 AND id = $2
`

type GetAirbyteSourceByIDParams struct {
	Org string
	ID  pgtype.UUID
}

func (q *Queries) GetAirbyteSourceByID(ctx context.Context, arg GetAirbyteSourceByIDParams) (AirbyteSource, error) {
	row := q.db.QueryRow(ctx, getAirbyteSourceByID, arg.Org, arg.ID)
	var i AirbyteSource
	err := row.Scan(
		&i.ID,
		&i.Org,
		&i.Name,
		&i.Connector,
		&i.ConfigEnc,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAirbyteStagedRecord = `-- name: InsertAirbyteStagedRecord :one
INSERT INTO airbyte_staged_records (org, source_id, stream, data)
VALUES ($1, $2, $3, $4)
RETURNING id, org, source_id, stream, data, ingested_at
`

type InsertAirbyteStagedRecordParams struct {
	Org      string
	SourceID pgtype.UUID
	Stream   string
	Data     []byte
}

func (q *Queries) InsertAirbyteStagedRecord(ctx context.Context, arg InsertAirbyteStagedRecordParams) (AirbyteStagedRecord, error) {
	row := q.db.QueryRow(ctx, insertAirbyteStagedRecord,
		arg.Org,
		arg.SourceID,
		arg.Stream,
		arg.Data,
	)
	var i AirbyteStagedRecord
	err := row.Scan(
		&i.ID,
		&i.Org,
		&i.SourceID,
		&i.Stream,
		&i.Data,
		&i.IngestedAt,
	)
	return i, err
}

const listAirbyteSources = `-- name: ListAirbyteSources :many
SELECT id, org, name, connector, config_enc, created_at, updated_at
FROM airbyte_sources
WHERE org = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAirbyteSources(ctx context.Context, org string) ([]AirbyteSource, error) {
	rows, err := q.db.Query(ctx, listAirbyteSources, org)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AirbyteSource{}
	for rows.Next() {
		var i AirbyteSource
		if err := rows.Scan(
			&i.ID,
			&i.Org,
			&i.Name,
			&i.Connector,
			&i.ConfigEnc,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAirbyteSource = `-- name: UpsertAirbyteSource :one
INSERT INTO airbyte_sources (org, name, connector, config_enc)
VALUES ($1, $2, $3, $4)
ON CONFLICT (org, name) DO UPDATE
SET connector = EXCLUDED.connector,
    config_enc = EXCLUDED.config_enc,
    updated_at = NOW()
RETURNING id, org, name, connector, config_enc, created_at, updated_at
`

type UpsertAirbyteSourceParams struct {
	Org       string
	Name      string
	Connector string
	ConfigEnc []byte
}

func (q *Queries) UpsertAirbyteSource(ctx context.Context, arg UpsertAirbyteSourceParams) (AirbyteSource, error) {
	row := q.db.QueryRow(ctx, upsertAirbyteSource,
		arg.Org,
		arg.Name,
		arg.Connector,
		arg.ConfigEnc,
	)
	var i AirbyteSource
	err := row.Scan(
		&i.ID,
		&i.Org,
		&i.Name,
		&i.Connector,
		&i.ConfigEnc,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
