// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: change.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRecentBreakingChanges = `-- name: CountRecentBreakingChanges :one
SELECT COUNT(*)
FROM breaking_change_history
WHERE repo_id = $1 AND timestamp >= $2
`

type CountRecentBreakingChangesParams struct {
	RepoID    pgtype.UUID
	Timestamp pgtype.Timestamptz
}

func (q *Queries) CountRecentBreakingChanges(ctx context.Context, arg CountRecentBreakingChangesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentBreakingChanges, arg.RepoID, arg.Timestamp)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBreakingChangeHistory = `-- name: GetBreakingChangeHistory :many
SELECT id, repo_id, org_name, repo_name, git_sha, timestamp, breaking_changes
FROM breaking_change_history
WHERE org_name = $1 AND repo_name = $2
ORDER BY timestamp DESC
LIMIT $3
`

type GetBreakingChangeHistoryParams struct {
	OrgName  string
	RepoName string
	Limit    int32
}

func (q *Queries) GetBreakingChangeHistory(ctx context.Context, arg GetBreakingChangeHistoryParams) ([]BreakingChangeHistory, error) {
	rows, err := q.db.Query(ctx, getBreakingChangeHistory, arg.OrgName, arg.RepoName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BreakingChangeHistory{}
	for rows.Next() {
		var i BreakingChangeHistory
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.OrgName,
			&i.RepoName,
			&i.GitSha,
			&i.Timestamp,
			&i.BreakingChanges,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBreakingChangesBetween = `-- name: GetBreakingChangesBetween :many
SELECT id, repo_id, org_name, repo_name, git_sha, timestamp, breaking_changes
FROM breaking_change_history
WHERE timestamp >= $1 AND timestamp <= $2
ORDER BY timestamp DESC
`

type GetBreakingChangesBetweenParams struct {
	Timestamp   pgtype.Timestamptz
	Timestamp_2 pgtype.Timestamptz
}

func (q *Queries) GetBreakingChangesBetween(ctx context.Context, arg GetBreakingChangesBetweenParams) ([]BreakingChangeHistory, error) {
	rows, err := q.db.Query(ctx, getBreakingChangesBetween, arg.Timestamp, arg.Timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BreakingChangeHistory{}
	for rows.Next() {
		var i BreakingChangeHistory
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.OrgName,
			&i.RepoName,
			&i.GitSha,
			&i.Timestamp,
			&i.BreakingChanges,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommitVelocity = `-- name: GetCommitVelocity :one
SELECT COUNT(*)
FROM contracts
WHERE repo_id = $1 AND synced_at >= $2
`

type GetCommitVelocityParams struct {
	RepoID   pgtype.UUID
	SyncedAt pgtype.Timestamptz
}

func (q *Queries) GetCommitVelocity(ctx context.Context, arg GetCommitVelocityParams) (int64, error) {
	row := q.db.QueryRow(ctx, getCommitVelocity, arg.RepoID, arg.SyncedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTimeSinceLastBreak = `-- name: GetTimeSinceLastBreak :one
SELECT MAX(timestamp)
FROM breaking_change_history
WHERE repo_id = $1
`

func (q *Queries) GetTimeSinceLastBreak(ctx context.Context, repoID pgtype.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, getTimeSinceLastBreak, repoID)
	var max interface{}
	err := row.Scan(&max)
	return max, err
}

const recordBreakingChange = `-- name: RecordBreakingChange :exec
INSERT INTO breaking_change_history (repo_id, org_name, repo_name, git_sha, breaking_changes)
VALUES ($1, $2, $3, $4, $5)
`

type RecordBreakingChangeParams struct {
	RepoID          pgtype.UUID
	OrgName         string
	RepoName        string
	GitSha          string
	BreakingChanges []byte
}

func (q *Queries) RecordBreakingChange(ctx context.Context, arg RecordBreakingChangeParams) error {
	_, err := q.db.Exec(ctx, recordBreakingChange,
		arg.RepoID,
		arg.OrgName,
		arg.RepoName,
		arg.GitSha,
		arg.BreakingChanges,
	)
	return err
}
