// Copyright (c) 2026 Krushna Vardhan Reddy. All rights reserved.
// PROPRIETARY AND CONFIDENTIAL — Substrate Cloud Platform.
// Unauthorized copying, modification, or distribution is strictly prohibited.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contract.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getConsumersByProviderContract = `-- name: GetConsumersByProviderContract :many
SELECT
  d.consumer_repo_id,
  r.full_name         AS consumer_full_name,
  c.raw_content       AS contract_raw_content,
  d.required_notice_days
FROM dependencies d
JOIN repositories r ON d.consumer_repo_id = r.id
JOIN contracts    c ON c.repo_id = r.id
WHERE d.provider_contract_id = $1
`

type GetConsumersByProviderContractRow struct {
	ConsumerRepoID     pgtype.UUID
	ConsumerFullName   string
	ContractRawContent pgtype.Text
	RequiredNoticeDays int32
}

func (q *Queries) GetConsumersByProviderContract(ctx context.Context, providerContractID pgtype.UUID) ([]GetConsumersByProviderContractRow, error) {
	rows, err := q.db.Query(ctx, getConsumersByProviderContract, providerContractID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetConsumersByProviderContractRow{}
	for rows.Next() {
		var i GetConsumersByProviderContractRow
		if err := rows.Scan(
			&i.ConsumerRepoID,
			&i.ConsumerFullName,
			&i.ContractRawContent,
			&i.RequiredNoticeDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContractsByProviderFullName = `-- name: GetContractsByProviderFullName :many
SELECT c.id, c.repo_id, c.schema_type, c.spec_path, c.branch,
       c.latest_commit_sha, c.raw_content, c.synced_at,
       c.is_encrypted, COALESCE(c.kms_key_arn, '') AS kms_key_arn
FROM contracts c
JOIN repositories r ON c.repo_id = r.id
WHERE r.full_name = $1
`

type GetContractsByProviderFullNameRow struct {
	ID              pgtype.UUID
	RepoID          pgtype.UUID
	SchemaType      string
	SpecPath        string
	Branch          string
	LatestCommitSha pgtype.Text
	RawContent      pgtype.Text
	SyncedAt        pgtype.Timestamptz
	IsEncrypted     pgtype.Bool
	KmsKeyArn       string
}

func (q *Queries) GetContractsByProviderFullName(ctx context.Context, fullName string) ([]GetContractsByProviderFullNameRow, error) {
	rows, err := q.db.Query(ctx, getContractsByProviderFullName, fullName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetContractsByProviderFullNameRow{}
	for rows.Next() {
		var i GetContractsByProviderFullNameRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.SchemaType,
			&i.SpecPath,
			&i.Branch,
			&i.LatestCommitSha,
			&i.RawContent,
			&i.SyncedAt,
			&i.IsEncrypted,
			&i.KmsKeyArn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertContract = `-- name: UpsertContract :one
INSERT INTO contracts (repo_id, schema_type, spec_path, branch, latest_commit_sha, raw_content, synced_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
ON CONFLICT (repo_id, spec_path, branch) DO UPDATE
  SET schema_type       = EXCLUDED.schema_type,
      latest_commit_sha = EXCLUDED.latest_commit_sha,
      raw_content       = EXCLUDED.raw_content,
      synced_at         = NOW()
RETURNING id
`

type UpsertContractParams struct {
	RepoID          pgtype.UUID
	SchemaType      string
	SpecPath        string
	Branch          string
	LatestCommitSha pgtype.Text
	RawContent      pgtype.Text
}

func (q *Queries) UpsertContract(ctx context.Context, arg UpsertContractParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertContract,
		arg.RepoID,
		arg.SchemaType,
		arg.SpecPath,
		arg.Branch,
		arg.LatestCommitSha,
		arg.RawContent,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
