// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: dependency.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDownstreamDependencies = `-- name: CountDownstreamDependencies :one
SELECT COUNT(*)
FROM dependencies d
JOIN contracts c ON d.provider_contract_id = c.id
JOIN repositories r ON c.repo_id = r.id
WHERE r.full_name = $1
`

func (q *Queries) CountDownstreamDependencies(ctx context.Context, fullName string) (int64, error) {
	row := q.db.QueryRow(ctx, countDownstreamDependencies, fullName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateDependencyConfidence = `-- name: UpdateDependencyConfidence :exec
UPDATE dependencies
SET confidence_score = confidence_score + $3
FROM contracts c
JOIN repositories r ON c.repo_id = r.id
WHERE dependencies.provider_contract_id = c.id
  AND r.full_name = $1
  AND c.spec_path LIKE '%' || $2 || '%'
`

type UpdateDependencyConfidenceParams struct {
	FullName        string
	Column2         pgtype.Text
	ConfidenceScore pgtype.Int4
}

func (q *Queries) UpdateDependencyConfidence(ctx context.Context, arg UpdateDependencyConfidenceParams) error {
	_, err := q.db.Exec(ctx, updateDependencyConfidence, arg.FullName, arg.Column2, arg.ConfidenceScore)
	return err
}

const updateDependencyStatus = `-- name: UpdateDependencyStatus :exec
UPDATE dependencies
SET status = $3
WHERE consumer_repo_id = $1
  AND provider_contract_id = $2
`

type UpdateDependencyStatusParams struct {
	ConsumerRepoID     pgtype.UUID
	ProviderContractID pgtype.UUID
	Status             string
}

func (q *Queries) UpdateDependencyStatus(ctx context.Context, arg UpdateDependencyStatusParams) error {
	_, err := q.db.Exec(ctx, updateDependencyStatus, arg.ConsumerRepoID, arg.ProviderContractID, arg.Status)
	return err
}

const upsertDependency = `-- name: UpsertDependency :exec
INSERT INTO dependencies (consumer_repo_id, provider_contract_id, confidence_score, required_notice_days)
VALUES ($1, $2, $3, $4)
ON CONFLICT (consumer_repo_id, provider_contract_id) DO UPDATE
  SET confidence_score    = GREATEST(dependencies.confidence_score, EXCLUDED.confidence_score),
      required_notice_days = EXCLUDED.required_notice_days
`

type UpsertDependencyParams struct {
	ConsumerRepoID     pgtype.UUID
	ProviderContractID pgtype.UUID
	ConfidenceScore    pgtype.Int4
	RequiredNoticeDays int32
}

func (q *Queries) UpsertDependency(ctx context.Context, arg UpsertDependencyParams) error {
	_, err := q.db.Exec(ctx, upsertDependency,
		arg.ConsumerRepoID,
		arg.ProviderContractID,
		arg.ConfidenceScore,
		arg.RequiredNoticeDays,
	)
	return err
}
