// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: diff.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPreviewSession = `-- name: CreatePreviewSession :one
INSERT INTO preview_sessions (pr_number, diff_id, expires_at)
VALUES ($1, $2, $3)
RETURNING token
`

type CreatePreviewSessionParams struct {
	PrNumber  int32
	DiffID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreatePreviewSession(ctx context.Context, arg CreatePreviewSessionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createPreviewSession, arg.PrNumber, arg.DiffID, arg.ExpiresAt)
	var token pgtype.UUID
	err := row.Scan(&token)
	return token, err
}

const expirePreviewSessionsForPR = `-- name: ExpirePreviewSessionsForPR :exec
UPDATE preview_sessions
SET expires_at = NOW() - INTERVAL '1 second'
WHERE pr_number = $1
  AND expires_at > NOW()
`

func (q *Queries) ExpirePreviewSessionsForPR(ctx context.Context, prNumber int32) error {
	_, err := q.db.Exec(ctx, expirePreviewSessionsForPR, prNumber)
	return err
}

const getDiffReport = `-- name: GetDiffReport :one
SELECT report_data FROM diff_reports WHERE id = $1
`

func (q *Queries) GetDiffReport(ctx context.Context, id pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getDiffReport, id)
	var report_data []byte
	err := row.Scan(&report_data)
	return report_data, err
}

const getDiffReportsByRepo = `-- name: GetDiffReportsByRepo :many
SELECT report_data, created_at
FROM diff_reports
WHERE org_name = $1 AND repo_name = $2
ORDER BY created_at DESC
LIMIT $3
`

type GetDiffReportsByRepoParams struct {
	OrgName  pgtype.Text
	RepoName pgtype.Text
	Limit    int32
}

type GetDiffReportsByRepoRow struct {
	ReportData []byte
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) GetDiffReportsByRepo(ctx context.Context, arg GetDiffReportsByRepoParams) ([]GetDiffReportsByRepoRow, error) {
	rows, err := q.db.Query(ctx, getDiffReportsByRepo, arg.OrgName, arg.RepoName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDiffReportsByRepoRow{}
	for rows.Next() {
		var i GetDiffReportsByRepoRow
		if err := rows.Scan(&i.ReportData, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPreviewSession = `-- name: GetPreviewSession :one
SELECT d.report_data, ps.expires_at
FROM preview_sessions ps
JOIN diff_reports d ON ps.diff_id = d.id
WHERE ps.token = $1
`

type GetPreviewSessionRow struct {
	ReportData []byte
	ExpiresAt  pgtype.Timestamptz
}

func (q *Queries) GetPreviewSession(ctx context.Context, token pgtype.UUID) (GetPreviewSessionRow, error) {
	row := q.db.QueryRow(ctx, getPreviewSession, token)
	var i GetPreviewSessionRow
	err := row.Scan(&i.ReportData, &i.ExpiresAt)
	return i, err
}

const saveDiffReport = `-- name: SaveDiffReport :one
INSERT INTO diff_reports (report_data, is_audit_mode, org_name, repo_name)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type SaveDiffReportParams struct {
	ReportData  []byte
	IsAuditMode pgtype.Bool
	OrgName     pgtype.Text
	RepoName    pgtype.Text
}

func (q *Queries) SaveDiffReport(ctx context.Context, arg SaveDiffReportParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, saveDiffReport,
		arg.ReportData,
		arg.IsAuditMode,
		arg.OrgName,
		arg.RepoName,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
