// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEcosystemEventsByOrg = `-- name: GetEcosystemEventsByOrg :many
SELECT id, org, repo, event_type, description, event_time, created_at FROM ecosystem_events
WHERE org = $1
AND event_time >= $2
AND event_time <= $3
ORDER BY event_time DESC
`

type GetEcosystemEventsByOrgParams struct {
	Org         string
	EventTime   time.Time
	EventTime_2 time.Time
}

func (q *Queries) GetEcosystemEventsByOrg(ctx context.Context, arg GetEcosystemEventsByOrgParams) ([]EcosystemEvent, error) {
	rows, err := q.db.Query(ctx, getEcosystemEventsByOrg, arg.Org, arg.EventTime, arg.EventTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EcosystemEvent{}
	for rows.Next() {
		var i EcosystemEvent
		if err := rows.Scan(
			&i.ID,
			&i.Org,
			&i.Repo,
			&i.EventType,
			&i.Description,
			&i.EventTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEcosystemEvent = `-- name: InsertEcosystemEvent :one
INSERT INTO ecosystem_events (
  org, repo, event_type, description, event_time
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, org, repo, event_type, description, event_time, created_at
`

type InsertEcosystemEventParams struct {
	Org         string
	Repo        string
	EventType   string
	Description pgtype.Text
	EventTime   time.Time
}

func (q *Queries) InsertEcosystemEvent(ctx context.Context, arg InsertEcosystemEventParams) (EcosystemEvent, error) {
	row := q.db.QueryRow(ctx, insertEcosystemEvent,
		arg.Org,
		arg.Repo,
		arg.EventType,
		arg.Description,
		arg.EventTime,
	)
	var i EcosystemEvent
	err := row.Scan(
		&i.ID,
		&i.Org,
		&i.Repo,
		&i.EventType,
		&i.Description,
		&i.EventTime,
		&i.CreatedAt,
	)
	return i, err
}
