// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fuzzer.sql

package sqlcgen

import (
	"context"
)

const getSchemaValidationGaps = `-- name: GetSchemaValidationGaps :many
SELECT id, method, path, payload, issue, severity, created_at FROM schema_validation_gaps ORDER BY created_at DESC
`

func (q *Queries) GetSchemaValidationGaps(ctx context.Context) ([]SchemaValidationGap, error) {
	rows, err := q.db.Query(ctx, getSchemaValidationGaps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SchemaValidationGap{}
	for rows.Next() {
		var i SchemaValidationGap
		if err := rows.Scan(
			&i.ID,
			&i.Method,
			&i.Path,
			&i.Payload,
			&i.Issue,
			&i.Severity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSchemaValidationGap = `-- name: InsertSchemaValidationGap :exec
INSERT INTO schema_validation_gaps (method, path, payload, issue, severity)
VALUES ($1, $2, $3, $4, $5)
`

type InsertSchemaValidationGapParams struct {
	Method   string
	Path     string
	Payload  []byte
	Issue    string
	Severity string
}

func (q *Queries) InsertSchemaValidationGap(ctx context.Context, arg InsertSchemaValidationGapParams) error {
	_, err := q.db.Exec(ctx, insertSchemaValidationGap,
		arg.Method,
		arg.Path,
		arg.Payload,
		arg.Issue,
		arg.Severity,
	)
	return err
}
