// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: governance.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteGovernanceRule = `-- name: DeleteGovernanceRule :exec
DELETE FROM governance_rules
WHERE id = $1 AND org_id = $2
`

type DeleteGovernanceRuleParams struct {
	ID    pgtype.UUID
	OrgID pgtype.UUID
}

func (q *Queries) DeleteGovernanceRule(ctx context.Context, arg DeleteGovernanceRuleParams) error {
	_, err := q.db.Exec(ctx, deleteGovernanceRule, arg.ID, arg.OrgID)
	return err
}

const getGovernanceRulesByOrg = `-- name: GetGovernanceRulesByOrg :many
SELECT id, org_id, rule_text, created_at
FROM governance_rules
WHERE org_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetGovernanceRulesByOrg(ctx context.Context, orgID pgtype.UUID) ([]GovernanceRule, error) {
	rows, err := q.db.Query(ctx, getGovernanceRulesByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GovernanceRule{}
	for rows.Next() {
		var i GovernanceRule
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.RuleText,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrgIDByName = `-- name: GetOrgIDByName :one
SELECT id FROM organizations WHERE github_org_name = $1
`

func (q *Queries) GetOrgIDByName(ctx context.Context, githubOrgName string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getOrgIDByName, githubOrgName)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertGovernanceRule = `-- name: UpsertGovernanceRule :one
INSERT INTO governance_rules (org_id, rule_text)
VALUES ($1, $2)
RETURNING id
`

type UpsertGovernanceRuleParams struct {
	OrgID    pgtype.UUID
	RuleText string
}

func (q *Queries) UpsertGovernanceRule(ctx context.Context, arg UpsertGovernanceRuleParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertGovernanceRule, arg.OrgID, arg.RuleText)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
