// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: insurance.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInsuranceClaim = `-- name: CreateInsuranceClaim :one
INSERT INTO insurance_claims (id, org_id, policy_id, github_pr_url, incident_date, status, amount_cents)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type CreateInsuranceClaimParams struct {
	ID           pgtype.UUID
	OrgID        pgtype.UUID
	PolicyID     pgtype.UUID
	GithubPrUrl  string
	IncidentDate pgtype.Timestamptz
	Status       string
	AmountCents  int64
}

func (q *Queries) CreateInsuranceClaim(ctx context.Context, arg CreateInsuranceClaimParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createInsuranceClaim,
		arg.ID,
		arg.OrgID,
		arg.PolicyID,
		arg.GithubPrUrl,
		arg.IncidentDate,
		arg.Status,
		arg.AmountCents,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getInsuranceClaims = `-- name: GetInsuranceClaims :many
SELECT id, org_id, policy_id, github_pr_url, incident_date, status, amount_cents, created_at, updated_at
FROM insurance_claims
WHERE org_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetInsuranceClaims(ctx context.Context, orgID pgtype.UUID) ([]InsuranceClaim, error) {
	rows, err := q.db.Query(ctx, getInsuranceClaims, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InsuranceClaim{}
	for rows.Next() {
		var i InsuranceClaim
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.PolicyID,
			&i.GithubPrUrl,
			&i.IncidentDate,
			&i.Status,
			&i.AmountCents,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInsurancePolicy = `-- name: GetInsurancePolicy :one
SELECT id, org_id, policy_limit_cents, created_at, updated_at
FROM insurance_policies
WHERE org_id = $1
`

func (q *Queries) GetInsurancePolicy(ctx context.Context, orgID pgtype.UUID) (InsurancePolicy, error) {
	row := q.db.QueryRow(ctx, getInsurancePolicy, orgID)
	var i InsurancePolicy
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.PolicyLimitCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertInsurancePolicy = `-- name: UpsertInsurancePolicy :one
INSERT INTO insurance_policies (org_id, policy_limit_cents)
VALUES ($1, $2)
ON CONFLICT (org_id) DO UPDATE
  SET policy_limit_cents = $2, updated_at = NOW()
RETURNING id
`

type UpsertInsurancePolicyParams struct {
	OrgID            pgtype.UUID
	PolicyLimitCents int64
}

func (q *Queries) UpsertInsurancePolicy(ctx context.Context, arg UpsertInsurancePolicyParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertInsurancePolicy, arg.OrgID, arg.PolicyLimitCents)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
