// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: marketplace.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listPlugins = `-- name: ListPlugins :many
SELECT id, name, description, schema_content, created_at, updated_at
FROM marketplace_plugins
ORDER BY name
`

func (q *Queries) ListPlugins(ctx context.Context) ([]MarketplacePlugin, error) {
	rows, err := q.db.Query(ctx, listPlugins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketplacePlugin{}
	for rows.Next() {
		var i MarketplacePlugin
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.SchemaContent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishPlugin = `-- name: PublishPlugin :one
INSERT INTO marketplace_plugins (name, description, schema_content)
VALUES ($1, $2, $3)
ON CONFLICT (name) DO UPDATE
  SET description    = EXCLUDED.description,
      schema_content = EXCLUDED.schema_content,
      updated_at     = NOW()
RETURNING id
`

type PublishPluginParams struct {
	Name          string
	Description   string
	SchemaContent []byte
}

func (q *Queries) PublishPlugin(ctx context.Context, arg PublishPluginParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, publishPlugin, arg.Name, arg.Description, arg.SchemaContent)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
