// Copyright (c) 2026 Krushna Vardhan Reddy. All rights reserved.
// PROPRIETARY AND CONFIDENTIAL — Substrate Cloud Platform.
// Unauthorized copying, modification, or distribution is strictly prohibited.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp_audit.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertMCPAuditLog = `-- name: InsertMCPAuditLog :one
INSERT INTO mcp_audit_logs (
    agent_id, tool_name, request_payload, response_payload
) VALUES (
    $1, $2, $3, $4
) RETURNING id
`

type InsertMCPAuditLogParams struct {
	AgentID         pgtype.Int4
	ToolName        string
	RequestPayload  []byte
	ResponsePayload []byte
}

func (q *Queries) InsertMCPAuditLog(ctx context.Context, arg InsertMCPAuditLogParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertMCPAuditLog,
		arg.AgentID,
		arg.ToolName,
		arg.RequestPayload,
		arg.ResponsePayload,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const listMCPAuditLogs = `-- name: ListMCPAuditLogs :many
SELECT id, agent_id, tool_name, request_payload, response_payload, executed_at
FROM mcp_audit_logs
ORDER BY executed_at DESC
`

func (q *Queries) ListMCPAuditLogs(ctx context.Context) ([]McpAuditLog, error) {
	rows, err := q.db.Query(ctx, listMCPAuditLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []McpAuditLog{}
	for rows.Next() {
		var i McpAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.ToolName,
			&i.RequestPayload,
			&i.ResponsePayload,
			&i.ExecutedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
