// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type RiverJobState string

const (
	RiverJobStateAvailable RiverJobState = "available"
	RiverJobStateCancelled RiverJobState = "cancelled"
	RiverJobStateCompleted RiverJobState = "completed"
	RiverJobStateDiscarded RiverJobState = "discarded"
	RiverJobStatePending   RiverJobState = "pending"
	RiverJobStateRetryable RiverJobState = "retryable"
	RiverJobStateRunning   RiverJobState = "running"
	RiverJobStateScheduled RiverJobState = "scheduled"
)

func (e *RiverJobState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RiverJobState(s)
	case string:
		*e = RiverJobState(s)
	default:
		return fmt.Errorf("unsupported scan type for RiverJobState: %T", src)
	}
	return nil
}

type NullRiverJobState struct {
	RiverJobState RiverJobState
	Valid         bool // Valid is true if RiverJobState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiverJobState) Scan(value interface{}) error {
	if value == nil {
		ns.RiverJobState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RiverJobState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiverJobState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RiverJobState), nil
}

type AgentConsumer struct {
	ID        pgtype.UUID
	RepoName  string
	Owner     string
	CreatedAt pgtype.Timestamptz
}

type AgentProfile struct {
	ID           int32
	Org          string
	Name         string
	AllowedTools []string
	HitlEnabled  bool
	CreatedAt    time.Time
}

type AgentToolDependency struct {
	ID              pgtype.UUID
	AgentID         pgtype.UUID
	ToolName        string
	ParametersJsonb []byte
	CreatedAt       pgtype.Timestamptz
}

type ApiKey struct {
	ID         pgtype.UUID
	OrgID      pgtype.UUID
	Name       string
	Prefix     string
	Hash       string
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
}

type BreakingChangeHistory struct {
	ID              pgtype.UUID
	RepoID          pgtype.UUID
	OrgName         string
	RepoName        string
	GitSha          string
	Timestamp       pgtype.Timestamptz
	BreakingChanges []byte
}

type ConsumerManifest struct {
	ID             pgtype.UUID
	ProviderRepo   string
	ConsumerRepo   string
	ConsumedFields []byte
	CreatedAt      pgtype.Timestamptz
}

type Contract struct {
	ID               pgtype.UUID
	RepoID           pgtype.UUID
	SchemaType       string
	SpecPath         string
	Branch           string
	LatestCommitSha  pgtype.Text
	RawContent       pgtype.Text
	SyncedAt         pgtype.Timestamptz
	EncryptedContent []byte
	IsEncrypted      pgtype.Bool
	KmsKeyArn        pgtype.Text
}

type Dependency struct {
	ID                 pgtype.UUID
	ConsumerRepoID     pgtype.UUID
	ProviderContractID pgtype.UUID
	Status             string
	LastCheckedAt      pgtype.Timestamptz
	ConfidenceScore    pgtype.Int4
	RequiredNoticeDays int32
}

type DiffReport struct {
	ID          pgtype.UUID
	ReportData  []byte
	CreatedAt   pgtype.Timestamptz
	IsAuditMode pgtype.Bool
	OrgName     pgtype.Text
	RepoName    pgtype.Text
}

type DriftAnomaly struct {
	ID           pgtype.UUID
	OrgName      string
	RepoName     string
	Method       string
	Path         string
	ErrorMessage string
	Timestamp    pgtype.Timestamptz
}

type EcosystemEvent struct {
	ID          int32
	Org         string
	Repo        string
	EventType   string
	Description pgtype.Text
	EventTime   time.Time
	CreatedAt   time.Time
}

type EndpointTraffic struct {
	ID           pgtype.UUID
	RepoID       pgtype.UUID
	Method       string
	Path         string
	LastSeenAt   pgtype.Timestamptz
	RequestCount pgtype.Int4
	CreatedAt    pgtype.Timestamptz
}

type GatewayConfig struct {
	ID          int32
	Org         string
	Repo        string
	GatewayType string
	CrdYaml     string
	PrUrl       pgtype.Text
	GeneratedAt time.Time
}

type GovernanceRule struct {
	ID        pgtype.UUID
	OrgID     pgtype.UUID
	RuleText  string
	CreatedAt pgtype.Timestamptz
}

type HitlQueue struct {
	ID         int32
	Org        string
	ProfileID  pgtype.Int4
	ToolName   string
	Arguments  []byte
	Status     string
	CreatedAt  time.Time
	ResolvedAt pgtype.Timestamptz
}

type InsuranceClaim struct {
	ID           pgtype.UUID
	OrgID        pgtype.UUID
	PolicyID     pgtype.UUID
	GithubPrUrl  string
	IncidentDate pgtype.Timestamptz
	Status       string
	AmountCents  int64
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type InsurancePolicy struct {
	ID               pgtype.UUID
	OrgID            pgtype.UUID
	PolicyLimitCents int64
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type MarketplacePlugin struct {
	ID            pgtype.UUID
	Name          string
	Description   string
	SchemaContent []byte
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type McpAuditLog struct {
	ID              int32
	AgentID         pgtype.Int4
	ToolName        string
	RequestPayload  []byte
	ResponsePayload []byte
	ExecutedAt      time.Time
}

type OrgIntegration struct {
	ID              pgtype.UUID
	OrgID           pgtype.UUID
	Provider        string
	ApiKeyEncrypted string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type OrgKmsConfig struct {
	OrgName   string
	Provider  string
	KeyArn    string
	CreatedAt pgtype.Timestamptz
}

type OrgWebhook struct {
	ID        pgtype.UUID
	Org       string
	Url       string
	Secret    pgtype.Text
	CreatedAt pgtype.Timestamptz
}

type Organization struct {
	ID                              pgtype.UUID
	GithubInstallationID            int64
	GithubOrgName                   string
	CreatedAt                       pgtype.Timestamptz
	TrialEndsAt                     pgtype.Timestamptz
	StripeCustomerID                pgtype.Text
	IsOss                           pgtype.Bool
	StripeApiKeyEncrypted           pgtype.Text
	SalesforceUrlEncrypted          pgtype.Text
	SalesforceTokenEncrypted        pgtype.Text
	SalesforceClientIDEncrypted     pgtype.Text
	SalesforceClientSecretEncrypted pgtype.Text
	SalesforceUsernameEncrypted     pgtype.Text
	SalesforcePasswordEncrypted     pgtype.Text
	QualityGate                     pgtype.Text
}

type PartnerIntegration struct {
	ID            pgtype.UUID
	VendorName    string
	Status        string
	WebhookUrl    string
	WebhookSecret string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type PreviewSession struct {
	Token     pgtype.UUID
	PrNumber  int32
	DiffID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type PublicNamespace struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

type PublicSchema struct {
	ID            pgtype.UUID
	NamespaceID   pgtype.UUID
	Name          string
	Version       string
	SchemaType    string
	SchemaContent string
	CreatedAt     pgtype.Timestamptz
}

type QaReplayJob struct {
	ID              pgtype.UUID
	RepoID          pgtype.UUID
	TimestampTarget pgtype.Timestamptz
	Status          string
	CoverageScore   pgtype.Numeric
	CreatedAt       pgtype.Timestamptz
	CompletedAt     pgtype.Timestamptz
}

type QaShadowTraffic struct {
	ID              pgtype.UUID
	RepoID          pgtype.UUID
	Method          string
	Path            string
	RequestPayload  []byte
	ResponsePayload []byte
	StatusCode      int32
	CapturedAt      pgtype.Timestamptz
}

type RepoCompliance struct {
	Org           string
	Repo          string
	Soc2Compliant bool
	HasPii        bool
}

type RepoGuide struct {
	ID        int32
	Org       string
	Repo      string
	FilePath  string
	Title     string
	Content   string
	UpdatedAt time.Time
}

type RepoMetric struct {
	ID                  pgtype.UUID
	RepoID              pgtype.UUID
	PredictiveRiskScore int32
	CalculatedAt        pgtype.Timestamptz
}

type Repository struct {
	ID           pgtype.UUID
	OrgID        pgtype.UUID
	GithubRepoID int64
	Name         string
	FullName     string
	CreatedAt    pgtype.Timestamptz
	Metadata     []byte
	BaseUrl      pgtype.Text
}

type RiverJob struct {
	ID           int64
	State        RiverJobState
	Attempt      int16
	MaxAttempts  int16
	AttemptedAt  pgtype.Timestamptz
	CreatedAt    time.Time
	FinalizedAt  pgtype.Timestamptz
	ScheduledAt  time.Time
	Priority     int16
	Args         []byte
	AttemptedBy  []string
	Errors       [][]byte
	Kind         string
	Metadata     []byte
	Queue        string
	Tags         []string
	UniqueKey    []byte
	UniqueStates pgtype.Bits
}

type RiverLeader struct {
	ElectedAt time.Time
	ExpiresAt time.Time
	LeaderID  string
	Name      string
}

type RiverMigration struct {
	ID        int64
	CreatedAt time.Time
	Version   int64
}

type RiverNotification struct {
	ID        int64
	CreatedAt time.Time
	Payload   string
	Topic     string
}

type RiverQueue struct {
	Name      string
	CreatedAt time.Time
	Metadata  []byte
	PausedAt  pgtype.Timestamptz
	UpdatedAt time.Time
}

type SandboxAuditLog struct {
	ID         int32
	Org        string
	Repo       string
	Method     string
	Path       string
	StatusCode pgtype.Int4
	UserID     string
	CreatedAt  time.Time
}

type SchemaPruneCache struct {
	Org          string
	Repo         string
	IntentHash   string
	PrunedSchema []byte
	ComputedAt   time.Time
}

type SchemaValidationGap struct {
	ID        pgtype.UUID
	Method    string
	Path      string
	Payload   []byte
	Issue     string
	Severity  string
	CreatedAt pgtype.Timestamptz
}

type ScorecardCache struct {
	Org        string
	Repo       string
	Grade      string
	Total      int32
	Breakdown  []byte
	ComputedAt time.Time
}
