// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: org.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countReposByOrg = `-- name: CountReposByOrg :one
SELECT COUNT(*) FROM repositories r
JOIN organizations o ON r.org_id = o.id
WHERE o.github_org_name = $1
`

func (q *Queries) CountReposByOrg(ctx context.Context, githubOrgName string) (int64, error) {
	row := q.db.QueryRow(ctx, countReposByOrg, githubOrgName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBillingStatus = `-- name: GetBillingStatus :one
SELECT trial_ends_at, stripe_customer_id
FROM organizations
WHERE github_org_name = $1
`

type GetBillingStatusRow struct {
	TrialEndsAt      pgtype.Timestamptz
	StripeCustomerID pgtype.Text
}

func (q *Queries) GetBillingStatus(ctx context.Context, githubOrgName string) (GetBillingStatusRow, error) {
	row := q.db.QueryRow(ctx, getBillingStatus, githubOrgName)
	var i GetBillingStatusRow
	err := row.Scan(&i.TrialEndsAt, &i.StripeCustomerID)
	return i, err
}

const getOrgKMSConfig = `-- name: GetOrgKMSConfig :one
SELECT provider, key_arn
FROM org_kms_config
WHERE org_name = $1
`

type GetOrgKMSConfigRow struct {
	Provider string
	KeyArn   string
}

func (q *Queries) GetOrgKMSConfig(ctx context.Context, orgName string) (GetOrgKMSConfigRow, error) {
	row := q.db.QueryRow(ctx, getOrgKMSConfig, orgName)
	var i GetOrgKMSConfigRow
	err := row.Scan(&i.Provider, &i.KeyArn)
	return i, err
}

const updateStripeCustomerID = `-- name: UpdateStripeCustomerID :exec
UPDATE organizations
SET stripe_customer_id = $1
WHERE id = $2
`

type UpdateStripeCustomerIDParams struct {
	StripeCustomerID pgtype.Text
	ID               pgtype.UUID
}

func (q *Queries) UpdateStripeCustomerID(ctx context.Context, arg UpdateStripeCustomerIDParams) error {
	_, err := q.db.Exec(ctx, updateStripeCustomerID, arg.StripeCustomerID, arg.ID)
	return err
}

const upsertOrg = `-- name: UpsertOrg :one
INSERT INTO organizations (github_installation_id, github_org_name, trial_ends_at)
VALUES ($1, $2, NOW() + INTERVAL '90 days')
ON CONFLICT (github_installation_id) DO UPDATE
  SET github_org_name = EXCLUDED.github_org_name
RETURNING id
`

type UpsertOrgParams struct {
	GithubInstallationID int64
	GithubOrgName        string
}

// Finds or creates an organization by github installation ID.
func (q *Queries) UpsertOrg(ctx context.Context, arg UpsertOrgParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertOrg, arg.GithubInstallationID, arg.GithubOrgName)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertOrgKMSConfig = `-- name: UpsertOrgKMSConfig :exec
INSERT INTO org_kms_config (org_name, provider, key_arn)
VALUES ($1, $2, $3)
ON CONFLICT (org_name) DO UPDATE
  SET provider = EXCLUDED.provider,
      key_arn  = EXCLUDED.key_arn
`

type UpsertOrgKMSConfigParams struct {
	OrgName  string
	Provider string
	KeyArn   string
}

func (q *Queries) UpsertOrgKMSConfig(ctx context.Context, arg UpsertOrgKMSConfigParams) error {
	_, err := q.db.Exec(ctx, upsertOrgKMSConfig, arg.OrgName, arg.Provider, arg.KeyArn)
	return err
}
