// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: org_integrations.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOrgIntegration = `-- name: GetOrgIntegration :one
SELECT id, org_id, provider, api_key_encrypted, created_at, updated_at
FROM org_integrations
WHERE org_id = $1 AND provider = $2
`

type GetOrgIntegrationParams struct {
	OrgID    pgtype.UUID
	Provider string
}

func (q *Queries) GetOrgIntegration(ctx context.Context, arg GetOrgIntegrationParams) (OrgIntegration, error) {
	row := q.db.QueryRow(ctx, getOrgIntegration, arg.OrgID, arg.Provider)
	var i OrgIntegration
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Provider,
		&i.ApiKeyEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOrgIntegration = `-- name: UpsertOrgIntegration :one
INSERT INTO org_integrations (org_id, provider, api_key_encrypted, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (org_id, provider) DO UPDATE
  SET api_key_encrypted = EXCLUDED.api_key_encrypted,
      updated_at = NOW()
RETURNING id, org_id, provider, api_key_encrypted, created_at, updated_at
`

type UpsertOrgIntegrationParams struct {
	OrgID           pgtype.UUID
	Provider        string
	ApiKeyEncrypted string
}

func (q *Queries) UpsertOrgIntegration(ctx context.Context, arg UpsertOrgIntegrationParams) (OrgIntegration, error) {
	row := q.db.QueryRow(ctx, upsertOrgIntegration, arg.OrgID, arg.Provider, arg.ApiKeyEncrypted)
	var i OrgIntegration
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Provider,
		&i.ApiKeyEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
