// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: partners.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPartner = `-- name: CreatePartner :one
INSERT INTO partner_integrations (vendor_name, webhook_url, webhook_secret)
VALUES ($1, $2, $3)
RETURNING id, vendor_name, status, webhook_url, webhook_secret, created_at, updated_at
`

type CreatePartnerParams struct {
	VendorName    string
	WebhookUrl    string
	WebhookSecret string
}

func (q *Queries) CreatePartner(ctx context.Context, arg CreatePartnerParams) (PartnerIntegration, error) {
	row := q.db.QueryRow(ctx, createPartner, arg.VendorName, arg.WebhookUrl, arg.WebhookSecret)
	var i PartnerIntegration
	err := row.Scan(
		&i.ID,
		&i.VendorName,
		&i.Status,
		&i.WebhookUrl,
		&i.WebhookSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePartner = `-- name: DeletePartner :one
DELETE FROM partner_integrations
WHERE id = $1
RETURNING id
`

func (q *Queries) DeletePartner(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deletePartner, id)
	err := row.Scan(&id)
	return id, err
}

const getPartner = `-- name: GetPartner :one
SELECT id, vendor_name, status, webhook_url, webhook_secret, created_at, updated_at
FROM partner_integrations
WHERE id = $1
`

func (q *Queries) GetPartner(ctx context.Context, id pgtype.UUID) (PartnerIntegration, error) {
	row := q.db.QueryRow(ctx, getPartner, id)
	var i PartnerIntegration
	err := row.Scan(
		&i.ID,
		&i.VendorName,
		&i.Status,
		&i.WebhookUrl,
		&i.WebhookSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPartners = `-- name: ListPartners :many
SELECT id, vendor_name, status, webhook_url, webhook_secret, created_at, updated_at
FROM partner_integrations
ORDER BY created_at DESC
`

func (q *Queries) ListPartners(ctx context.Context) ([]PartnerIntegration, error) {
	rows, err := q.db.Query(ctx, listPartners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PartnerIntegration{}
	for rows.Next() {
		var i PartnerIntegration
		if err := rows.Scan(
			&i.ID,
			&i.VendorName,
			&i.Status,
			&i.WebhookUrl,
			&i.WebhookSecret,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePartner = `-- name: UpdatePartner :one
UPDATE partner_integrations
SET
    vendor_name = COALESCE(NULLIF($1::text, ''), vendor_name),
    webhook_url = COALESCE(NULLIF($2::text, ''), webhook_url),
    webhook_secret = COALESCE(NULLIF($3::text, ''), webhook_secret),
    updated_at = NOW()
WHERE id = $4
RETURNING id, vendor_name, status, webhook_url, webhook_secret, created_at, updated_at
`

type UpdatePartnerParams struct {
	VendorName    string
	WebhookUrl    string
	WebhookSecret string
	ID            pgtype.UUID
}

func (q *Queries) UpdatePartner(ctx context.Context, arg UpdatePartnerParams) (PartnerIntegration, error) {
	row := q.db.QueryRow(ctx, updatePartner,
		arg.VendorName,
		arg.WebhookUrl,
		arg.WebhookSecret,
		arg.ID,
	)
	var i PartnerIntegration
	err := row.Scan(
		&i.ID,
		&i.VendorName,
		&i.Status,
		&i.WebhookUrl,
		&i.WebhookSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePartnerStatus = `-- name: UpdatePartnerStatus :one
UPDATE partner_integrations
SET status = $1, updated_at = NOW()
WHERE id = $2
RETURNING id, vendor_name, status, webhook_url, webhook_secret, created_at, updated_at
`

type UpdatePartnerStatusParams struct {
	Status string
	ID     pgtype.UUID
}

func (q *Queries) UpdatePartnerStatus(ctx context.Context, arg UpdatePartnerStatusParams) (PartnerIntegration, error) {
	row := q.db.QueryRow(ctx, updatePartnerStatus, arg.Status, arg.ID)
	var i PartnerIntegration
	err := row.Scan(
		&i.ID,
		&i.VendorName,
		&i.Status,
		&i.WebhookUrl,
		&i.WebhookSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
