// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_qa.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createQAReplayJob = `-- name: CreateQAReplayJob :one
INSERT INTO qa_replay_jobs (
    repo_id, timestamp_target, status
) VALUES (
    $1, $2, 'pending'
) RETURNING id
`

type CreateQAReplayJobParams struct {
	RepoID          pgtype.UUID
	TimestampTarget pgtype.Timestamptz
}

func (q *Queries) CreateQAReplayJob(ctx context.Context, arg CreateQAReplayJobParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createQAReplayJob, arg.RepoID, arg.TimestampTarget)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getLatestQAReplayJob = `-- name: GetLatestQAReplayJob :one
SELECT id, repo_id, timestamp_target, status, coverage_score, created_at, completed_at FROM qa_replay_jobs
WHERE repo_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestQAReplayJob(ctx context.Context, repoID pgtype.UUID) (QaReplayJob, error) {
	row := q.db.QueryRow(ctx, getLatestQAReplayJob, repoID)
	var i QaReplayJob
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.TimestampTarget,
		&i.Status,
		&i.CoverageScore,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getQAShadowTrafficByRepo = `-- name: GetQAShadowTrafficByRepo :many
SELECT id, repo_id, method, path, request_payload, response_payload, status_code, captured_at FROM qa_shadow_traffic
WHERE repo_id = $1
ORDER BY captured_at DESC
LIMIT 1000
`

func (q *Queries) GetQAShadowTrafficByRepo(ctx context.Context, repoID pgtype.UUID) ([]QaShadowTraffic, error) {
	rows, err := q.db.Query(ctx, getQAShadowTrafficByRepo, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QaShadowTraffic{}
	for rows.Next() {
		var i QaShadowTraffic
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Method,
			&i.Path,
			&i.RequestPayload,
			&i.ResponsePayload,
			&i.StatusCode,
			&i.CapturedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertQAShadowTraffic = `-- name: InsertQAShadowTraffic :exec
INSERT INTO qa_shadow_traffic (
    repo_id, method, path, request_payload, response_payload, status_code
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type InsertQAShadowTrafficParams struct {
	RepoID          pgtype.UUID
	Method          string
	Path            string
	RequestPayload  []byte
	ResponsePayload []byte
	StatusCode      int32
}

func (q *Queries) InsertQAShadowTraffic(ctx context.Context, arg InsertQAShadowTrafficParams) error {
	_, err := q.db.Exec(ctx, insertQAShadowTraffic,
		arg.RepoID,
		arg.Method,
		arg.Path,
		arg.RequestPayload,
		arg.ResponsePayload,
		arg.StatusCode,
	)
	return err
}

const updateQAReplayJobStatus = `-- name: UpdateQAReplayJobStatus :exec
UPDATE qa_replay_jobs
SET status = $1, coverage_score = $2, completed_at = NOW()
WHERE id = $3
`

type UpdateQAReplayJobStatusParams struct {
	Status        string
	CoverageScore pgtype.Numeric
	ID            pgtype.UUID
}

func (q *Queries) UpdateQAReplayJobStatus(ctx context.Context, arg UpdateQAReplayJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateQAReplayJobStatus, arg.Status, arg.CoverageScore, arg.ID)
	return err
}
