// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: repo.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllRepositories = `-- name: GetAllRepositories :many
SELECT id, org_id, github_repo_id, name, full_name, metadata, created_at
FROM repositories
`

type GetAllRepositoriesRow struct {
	ID           pgtype.UUID
	OrgID        pgtype.UUID
	GithubRepoID int64
	Name         string
	FullName     string
	Metadata     []byte
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) GetAllRepositories(ctx context.Context) ([]GetAllRepositoriesRow, error) {
	rows, err := q.db.Query(ctx, getAllRepositories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllRepositoriesRow{}
	for rows.Next() {
		var i GetAllRepositoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.GithubRepoID,
			&i.Name,
			&i.FullName,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDependencyGraph = `-- name: GetDependencyGraph :many
SELECT
  c_repo.full_name  AS consumer_full_name,
  p_repo.full_name  AS provider_full_name,
  d.status,
  c_repo.metadata   AS consumer_metadata,
  p_repo.metadata   AS provider_metadata,
  COALESCE(rm.predictive_risk_score, 0) AS predictive_risk_score
FROM dependencies d
JOIN contracts    p_c  ON d.provider_contract_id = p_c.id
JOIN repositories p_repo ON p_c.repo_id = p_repo.id
JOIN repositories c_repo ON d.consumer_repo_id   = c_repo.id
LEFT JOIN repo_metrics rm ON rm.repo_id = p_repo.id
JOIN organizations o ON p_repo.org_id = o.id
WHERE o.github_org_name = $1
`

type GetDependencyGraphRow struct {
	ConsumerFullName    string
	ProviderFullName    string
	Status              string
	ConsumerMetadata    []byte
	ProviderMetadata    []byte
	PredictiveRiskScore int32
}

func (q *Queries) GetDependencyGraph(ctx context.Context, githubOrgName string) ([]GetDependencyGraphRow, error) {
	rows, err := q.db.Query(ctx, getDependencyGraph, githubOrgName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDependencyGraphRow{}
	for rows.Next() {
		var i GetDependencyGraphRow
		if err := rows.Scan(
			&i.ConsumerFullName,
			&i.ProviderFullName,
			&i.Status,
			&i.ConsumerMetadata,
			&i.ProviderMetadata,
			&i.PredictiveRiskScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReposByOrg = `-- name: ListReposByOrg :many
SELECT r.id, r.org_id, r.github_repo_id, r.name, r.full_name, r.metadata, r.created_at
FROM repositories r
JOIN organizations o ON r.org_id = o.id
WHERE o.github_org_name = $1
ORDER BY r.name
`

type ListReposByOrgRow struct {
	ID           pgtype.UUID
	OrgID        pgtype.UUID
	GithubRepoID int64
	Name         string
	FullName     string
	Metadata     []byte
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) ListReposByOrg(ctx context.Context, githubOrgName string) ([]ListReposByOrgRow, error) {
	rows, err := q.db.Query(ctx, listReposByOrg, githubOrgName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReposByOrgRow{}
	for rows.Next() {
		var i ListReposByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.GithubRepoID,
			&i.Name,
			&i.FullName,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRepo = `-- name: UpsertRepo :one
INSERT INTO repositories (org_id, github_repo_id, name, full_name, metadata)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (github_repo_id) DO UPDATE
  SET name       = EXCLUDED.name,
      full_name  = EXCLUDED.full_name,
      org_id     = EXCLUDED.org_id,
      metadata   = EXCLUDED.metadata
RETURNING id
`

type UpsertRepoParams struct {
	OrgID        pgtype.UUID
	GithubRepoID int64
	Name         string
	FullName     string
	Metadata     []byte
}

func (q *Queries) UpsertRepo(ctx context.Context, arg UpsertRepoParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertRepo,
		arg.OrgID,
		arg.GithubRepoID,
		arg.Name,
		arg.FullName,
		arg.Metadata,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertRepoMetric = `-- name: UpsertRepoMetric :exec
INSERT INTO repo_metrics (repo_id, predictive_risk_score, calculated_at)
VALUES ($1, $2, NOW())
ON CONFLICT (repo_id) DO UPDATE
  SET predictive_risk_score = EXCLUDED.predictive_risk_score,
      calculated_at         = NOW()
`

type UpsertRepoMetricParams struct {
	RepoID              pgtype.UUID
	PredictiveRiskScore int32
}

func (q *Queries) UpsertRepoMetric(ctx context.Context, arg UpsertRepoMetricParams) error {
	_, err := q.db.Exec(ctx, upsertRepoMetric, arg.RepoID, arg.PredictiveRiskScore)
	return err
}
