// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sandbox.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRepoBaseURL = `-- name: GetRepoBaseURL :one
SELECT base_url FROM repositories WHERE org_id = $1 AND name = $2 LIMIT 1
`

type GetRepoBaseURLParams struct {
	OrgID pgtype.UUID
	Name  string
}

func (q *Queries) GetRepoBaseURL(ctx context.Context, arg GetRepoBaseURLParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getRepoBaseURL, arg.OrgID, arg.Name)
	var base_url pgtype.Text
	err := row.Scan(&base_url)
	return base_url, err
}

const insertSandboxAuditLog = `-- name: InsertSandboxAuditLog :exec
INSERT INTO sandbox_audit_log (org, repo, method, path, status_code, user_id)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertSandboxAuditLogParams struct {
	Org        string
	Repo       string
	Method     string
	Path       string
	StatusCode pgtype.Int4
	UserID     string
}

func (q *Queries) InsertSandboxAuditLog(ctx context.Context, arg InsertSandboxAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertSandboxAuditLog,
		arg.Org,
		arg.Repo,
		arg.Method,
		arg.Path,
		arg.StatusCode,
		arg.UserID,
	)
	return err
}
