// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: schema_prune_cache.sql

package sqlcgen

import (
	"context"
)

const getPrunedSchemaCache = `-- name: GetPrunedSchemaCache :one
SELECT org, repo, intent_hash, pruned_schema, computed_at
FROM schema_prune_cache
WHERE org = $1 AND repo = $2 AND intent_hash = $3 AND computed_at > NOW() - INTERVAL '30 minutes'
`

type GetPrunedSchemaCacheParams struct {
	Org        string
	Repo       string
	IntentHash string
}

func (q *Queries) GetPrunedSchemaCache(ctx context.Context, arg GetPrunedSchemaCacheParams) (SchemaPruneCache, error) {
	row := q.db.QueryRow(ctx, getPrunedSchemaCache, arg.Org, arg.Repo, arg.IntentHash)
	var i SchemaPruneCache
	err := row.Scan(
		&i.Org,
		&i.Repo,
		&i.IntentHash,
		&i.PrunedSchema,
		&i.ComputedAt,
	)
	return i, err
}

const upsertPrunedSchemaCache = `-- name: UpsertPrunedSchemaCache :exec
INSERT INTO schema_prune_cache (org, repo, intent_hash, pruned_schema, computed_at)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (org, repo, intent_hash) DO UPDATE
SET pruned_schema = EXCLUDED.pruned_schema,
    computed_at = EXCLUDED.computed_at
`

type UpsertPrunedSchemaCacheParams struct {
	Org          string
	Repo         string
	IntentHash   string
	PrunedSchema []byte
}

func (q *Queries) UpsertPrunedSchemaCache(ctx context.Context, arg UpsertPrunedSchemaCacheParams) error {
	_, err := q.db.Exec(ctx, upsertPrunedSchemaCache,
		arg.Org,
		arg.Repo,
		arg.IntentHash,
		arg.PrunedSchema,
	)
	return err
}
