// Copyright (c) 2026 Krushna Vardhan Reddy. All rights reserved.
// PROPRIETARY AND CONFIDENTIAL — Substrate Cloud Platform.
// Unauthorized copying, modification, or distribution is strictly prohibited.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scorecard.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestQACoverageScore = `-- name: GetLatestQACoverageScore :one
SELECT coverage_score
FROM qa_replay_jobs
WHERE repo_id = (SELECT id FROM repositories WHERE org_id = (SELECT id FROM organizations WHERE github_org_name = $1) AND name = $2)
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestQACoverageScoreParams struct {
	GithubOrgName string
	Name          string
}

func (q *Queries) GetLatestQACoverageScore(ctx context.Context, arg GetLatestQACoverageScoreParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getLatestQACoverageScore, arg.GithubOrgName, arg.Name)
	var coverage_score pgtype.Numeric
	err := row.Scan(&coverage_score)
	return coverage_score, err
}

const getRepoCompliance = `-- name: GetRepoCompliance :one
SELECT org, repo, soc2_compliant, has_pii FROM repo_compliance
WHERE org = $1 AND repo = $2
`

type GetRepoComplianceParams struct {
	Org  string
	Repo string
}

func (q *Queries) GetRepoCompliance(ctx context.Context, arg GetRepoComplianceParams) (RepoCompliance, error) {
	row := q.db.QueryRow(ctx, getRepoCompliance, arg.Org, arg.Repo)
	var i RepoCompliance
	err := row.Scan(
		&i.Org,
		&i.Repo,
		&i.Soc2Compliant,
		&i.HasPii,
	)
	return i, err
}

const getScorecardCache = `-- name: GetScorecardCache :one
SELECT org, repo, grade, total, breakdown, computed_at FROM scorecard_cache
WHERE org = $1 AND repo = $2
`

type GetScorecardCacheParams struct {
	Org  string
	Repo string
}

func (q *Queries) GetScorecardCache(ctx context.Context, arg GetScorecardCacheParams) (ScorecardCache, error) {
	row := q.db.QueryRow(ctx, getScorecardCache, arg.Org, arg.Repo)
	var i ScorecardCache
	err := row.Scan(
		&i.Org,
		&i.Repo,
		&i.Grade,
		&i.Total,
		&i.Breakdown,
		&i.ComputedAt,
	)
	return i, err
}

const hasRepoGuides = `-- name: HasRepoGuides :one
SELECT EXISTS (
    SELECT 1 FROM repo_guides
    WHERE org = $1 AND repo = $2
)
`

type HasRepoGuidesParams struct {
	Org  string
	Repo string
}

func (q *Queries) HasRepoGuides(ctx context.Context, arg HasRepoGuidesParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasRepoGuides, arg.Org, arg.Repo)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const upsertScorecardCache = `-- name: UpsertScorecardCache :exec
INSERT INTO scorecard_cache (org, repo, grade, total, breakdown, computed_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (org, repo) DO UPDATE
SET grade = EXCLUDED.grade,
    total = EXCLUDED.total,
    breakdown = EXCLUDED.breakdown,
    computed_at = NOW()
`

type UpsertScorecardCacheParams struct {
	Org       string
	Repo      string
	Grade     string
	Total     int32
	Breakdown []byte
}

func (q *Queries) UpsertScorecardCache(ctx context.Context, arg UpsertScorecardCacheParams) error {
	_, err := q.db.Exec(ctx, upsertScorecardCache,
		arg.Org,
		arg.Repo,
		arg.Grade,
		arg.Total,
		arg.Breakdown,
	)
	return err
}
