// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: telemetry.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDriftAnomalies = `-- name: GetDriftAnomalies :many
SELECT id, org_name, repo_name, method, path, error_message, timestamp
FROM drift_anomalies
WHERE org_name = $1 AND repo_name = $2
ORDER BY timestamp DESC
`

type GetDriftAnomaliesParams struct {
	OrgName  string
	RepoName string
}

func (q *Queries) GetDriftAnomalies(ctx context.Context, arg GetDriftAnomaliesParams) ([]DriftAnomaly, error) {
	rows, err := q.db.Query(ctx, getDriftAnomalies, arg.OrgName, arg.RepoName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DriftAnomaly{}
	for rows.Next() {
		var i DriftAnomaly
		if err := rows.Scan(
			&i.ID,
			&i.OrgName,
			&i.RepoName,
			&i.Method,
			&i.Path,
			&i.ErrorMessage,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getROIMetrics = `-- name: GetROIMetrics :one
SELECT
  (SELECT COUNT(*) FROM diff_reports
   WHERE (is_audit_mode = true OR report_data->>'status' = 'blocked')
     AND diff_reports.org_name = $1
     AND created_at > NOW() - INTERVAL '30 days')          AS total_prevented_outages,
  (SELECT COUNT(*) FROM drift_anomalies
   WHERE drift_anomalies.org_name = $1
     AND timestamp > NOW() - INTERVAL '30 days')          AS total_undocumented_endpoints
`

type GetROIMetricsRow struct {
	TotalPreventedOutages      int64
	TotalUndocumentedEndpoints int64
}

func (q *Queries) GetROIMetrics(ctx context.Context, orgName pgtype.Text) (GetROIMetricsRow, error) {
	row := q.db.QueryRow(ctx, getROIMetrics, orgName)
	var i GetROIMetricsRow
	err := row.Scan(&i.TotalPreventedOutages, &i.TotalUndocumentedEndpoints)
	return i, err
}

const getZeroTrafficEndpoints = `-- name: GetZeroTrafficEndpoints :many
SELECT et.id, et.repo_id, et.method, et.path, et.last_seen_at, et.request_count
FROM endpoint_traffic et
JOIN repositories r ON et.repo_id = r.id
JOIN organizations o ON r.org_id = o.id
WHERE o.github_org_name = $1
  AND (et.last_seen_at IS NULL OR et.last_seen_at < $2)
`

type GetZeroTrafficEndpointsParams struct {
	GithubOrgName string
	LastSeenAt    pgtype.Timestamptz
}

type GetZeroTrafficEndpointsRow struct {
	ID           pgtype.UUID
	RepoID       pgtype.UUID
	Method       string
	Path         string
	LastSeenAt   pgtype.Timestamptz
	RequestCount pgtype.Int4
}

func (q *Queries) GetZeroTrafficEndpoints(ctx context.Context, arg GetZeroTrafficEndpointsParams) ([]GetZeroTrafficEndpointsRow, error) {
	rows, err := q.db.Query(ctx, getZeroTrafficEndpoints, arg.GithubOrgName, arg.LastSeenAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetZeroTrafficEndpointsRow{}
	for rows.Next() {
		var i GetZeroTrafficEndpointsRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Method,
			&i.Path,
			&i.LastSeenAt,
			&i.RequestCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordDriftAnomaly = `-- name: RecordDriftAnomaly :exec
INSERT INTO drift_anomalies (org_name, repo_name, method, path, error_message)
VALUES ($1, $2, $3, $4, $5)
`

type RecordDriftAnomalyParams struct {
	OrgName      string
	RepoName     string
	Method       string
	Path         string
	ErrorMessage string
}

func (q *Queries) RecordDriftAnomaly(ctx context.Context, arg RecordDriftAnomalyParams) error {
	_, err := q.db.Exec(ctx, recordDriftAnomaly,
		arg.OrgName,
		arg.RepoName,
		arg.Method,
		arg.Path,
		arg.ErrorMessage,
	)
	return err
}

const upsertEndpointTraffic = `-- name: UpsertEndpointTraffic :exec
INSERT INTO endpoint_traffic (repo_id, method, path, last_seen_at, request_count)
VALUES ($1, $2, $3, $4, 1)
ON CONFLICT (repo_id, method, path) DO UPDATE
  SET last_seen_at  = GREATEST(endpoint_traffic.last_seen_at, EXCLUDED.last_seen_at),
      request_count = endpoint_traffic.request_count + 1
`

type UpsertEndpointTrafficParams struct {
	RepoID     pgtype.UUID
	Method     string
	Path       string
	LastSeenAt pgtype.Timestamptz
}

func (q *Queries) UpsertEndpointTraffic(ctx context.Context, arg UpsertEndpointTrafficParams) error {
	_, err := q.db.Exec(ctx, upsertEndpointTraffic,
		arg.RepoID,
		arg.Method,
		arg.Path,
		arg.LastSeenAt,
	)
	return err
}
