// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: webhook.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getWebhooks = `-- name: GetWebhooks :many
SELECT id::text, org, url, secret, created_at
FROM org_webhooks
WHERE org = $1
`

type GetWebhooksRow struct {
	ID        string
	Org       string
	Url       string
	Secret    pgtype.Text
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetWebhooks(ctx context.Context, org string) ([]GetWebhooksRow, error) {
	rows, err := q.db.Query(ctx, getWebhooks, org)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWebhooksRow{}
	for rows.Next() {
		var i GetWebhooksRow
		if err := rows.Scan(
			&i.ID,
			&i.Org,
			&i.Url,
			&i.Secret,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerWebhook = `-- name: RegisterWebhook :exec
INSERT INTO org_webhooks (org, url, secret)
VALUES ($1, $2, $3)
`

type RegisterWebhookParams struct {
	Org    string
	Url    string
	Secret pgtype.Text
}

func (q *Queries) RegisterWebhook(ctx context.Context, arg RegisterWebhookParams) error {
	_, err := q.db.Exec(ctx, registerWebhook, arg.Org, arg.Url, arg.Secret)
	return err
}
