FROM golang:1.22 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o substrate-api ./cmd/server/main.go

FROM debian:buster-slim

WORKDIR /app

COPY --from=builder /app/substrate-api /usr/local/bin/

EXPOSE 8090

CMD ["substrate-api"]
